//! DDL compilers: CREATE TABLE, DROP TABLE, CREATE INDEX, DROP INDEX.
//!
//! DDL statements don't bind params — they return plain SQL strings.

use crate::dialect::{ColumnTypeKind, ColumnTypeSpec, Dialect};
use serde::{Deserialize, Serialize};

/// Quote a value as a SQL string literal (`'x'`), doubling embedded single
/// quotes. Rejects NUL — no dialect accepts it inside a literal and it can
/// truncate the statement. Used for `ENUM(...)` / `CHECK (… IN (…))` values.
fn quote_str_literal(s: &str) -> Result<String, String> {
    if s.contains('\0') {
        return Err(format!(
            "E_UNSAFE_LITERAL: enum value contains a NUL byte: {:?}",
            s
        ));
    }
    Ok(format!("'{}'", s.replace('\'', "''")))
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateTableSpec {
    pub table: String,
    pub columns: Vec<ColumnDef>,
    #[serde(default)]
    pub indexes: Vec<IndexDef>,
    #[serde(default)]
    pub if_not_exists: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ColumnDef {
    pub name: String,
    #[serde(flatten)]
    pub type_spec: ColumnTypeSpec,
    #[serde(default)]
    pub nullable: bool,
    #[serde(default)]
    pub primary: bool,
    /// Dialect-appropriate auto-increment / identity column (Lucid `increments()`):
    /// SQLite `INTEGER PRIMARY KEY AUTOINCREMENT`, Postgres `GENERATED BY DEFAULT
    /// AS IDENTITY`, MySQL `AUTO_INCREMENT`. Implies PRIMARY KEY.
    #[serde(default)]
    pub auto_increment: bool,
    #[serde(default)]
    pub unique: bool,
    /// MySQL `UNSIGNED` numeric modifier (Lucid `unsigned()`). Ignored on
    /// Postgres and SQLite, which have no unsigned integer types.
    #[serde(default)]
    pub unsigned: bool,
    #[serde(default)]
    pub default: Option<String>,
    #[serde(default)]
    pub references: Option<ForeignKeyRef>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ForeignKeyRef {
    pub table: String,
    pub column: String,
    /// Referential action for `ON DELETE` (CASCADE / SET NULL / RESTRICT / NO ACTION / SET DEFAULT).
    #[serde(default)]
    pub on_delete: Option<String>,
    /// Referential action for `ON UPDATE`.
    #[serde(default)]
    pub on_update: Option<String>,
}

/// Validate + normalise a referential action against the SQL-standard allow-list.
/// Case-insensitive; returns the canonical upper-cased keyword.
fn referential_action(action: &str) -> Result<&'static str, String> {
    match action.to_uppercase().replace('_', " ").as_str() {
        "CASCADE" => Ok("CASCADE"),
        "SET NULL" => Ok("SET NULL"),
        "SET DEFAULT" => Ok("SET DEFAULT"),
        "RESTRICT" => Ok("RESTRICT"),
        "NO ACTION" => Ok("NO ACTION"),
        _ => Err(format!(
            "E_UNSAFE_SQL: invalid referential action '{}' (use CASCADE, SET NULL, SET DEFAULT, RESTRICT, or NO ACTION)",
            action
        )),
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IndexDef {
    pub name: String,
    pub columns: Vec<String>,
    #[serde(default)]
    pub unique: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DropTableSpec {
    pub table: String,
    #[serde(default)]
    pub if_exists: bool,
    /// Emit `CASCADE` so dependent foreign keys drop with the table. Honoured
    /// only on Postgres — SQLite rejects the keyword and MySQL treats it as a
    /// no-op (it relies on `SET FOREIGN_KEY_CHECKS = 0` instead).
    #[serde(default)]
    pub cascade: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateIndexSpec {
    pub table: String,
    pub name: String,
    pub columns: Vec<String>,
    #[serde(default)]
    pub unique: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DropIndexSpec {
    pub name: String,
    #[serde(default)]
    pub if_exists: bool,
}

/// Render a single column definition (`"name" TYPE [PRIMARY KEY] [NOT NULL] …
/// [REFERENCES …]`) — shared by CREATE TABLE and ALTER TABLE ADD/ALTER COLUMN.
fn render_column_def(col: &ColumnDef, dialect: Dialect) -> Result<String, String> {
    let mut parts: Vec<String> = vec![dialect.quote_ident(&col.name)?];
    if col.auto_increment {
        // Type + PRIMARY KEY + identity are one dialect-specific clause;
        // NOT NULL / UNIQUE / DEFAULT are subsumed by the identity column.
        parts.push(dialect.auto_increment_column(col.type_spec.kind));
    } else {
        if col.type_spec.kind == ColumnTypeKind::Enum {
            // MySQL has a native ENUM(...); pg/sqlite render TEXT + a CHECK that
            // pins the value set (Lucid's non-native enum behaviour).
            let values = col.type_spec.values.as_deref().unwrap_or(&[]);
            if values.is_empty() {
                return Err("E_ENUM_EMPTY: an enum column requires at least one value".into());
            }
            let literals = values
                .iter()
                .map(|v| quote_str_literal(v))
                .collect::<Result<Vec<_>, _>>()?
                .join(", ");
            match dialect {
                Dialect::Mysql => parts.push(format!("ENUM({})", literals)),
                _ => {
                    parts.push("TEXT".into());
                    parts.push(format!(
                        "CHECK ({} IN ({}))",
                        dialect.quote_ident(&col.name)?,
                        literals
                    ));
                }
            }
        } else {
            parts.push(dialect.map_column_type(&col.type_spec)?);
            // MySQL-only UNSIGNED modifier — directly after the numeric type.
            if col.unsigned && matches!(dialect, Dialect::Mysql) {
                parts.push("UNSIGNED".into());
            }
        }
        if col.primary { parts.push("PRIMARY KEY".into()); }
        if !col.nullable { parts.push("NOT NULL".into()); }
        if col.unique { parts.push("UNIQUE".into()); }
        if let Some(default) = &col.default {
            parts.push(dialect.wrap_default(default));
        }
    }
    if let Some(fk) = &col.references {
        parts.push(format!(
            "REFERENCES {}({})",
            dialect.quote_ident(&fk.table)?,
            dialect.quote_ident(&fk.column)?
        ));
        if let Some(action) = &fk.on_delete {
            parts.push(format!("ON DELETE {}", referential_action(action)?));
        }
        if let Some(action) = &fk.on_update {
            parts.push(format!("ON UPDATE {}", referential_action(action)?));
        }
    }
    Ok(parts.join(" "))
}

/// Compile CREATE TABLE → one or more SQL statements (the CREATE itself + CREATE INDEX for each index).
pub fn compile_create_table(spec: &CreateTableSpec, dialect: Dialect) -> Result<Vec<String>, String> {
    if spec.columns.is_empty() {
        return Err("CREATE TABLE requires at least one column".into());
    }
    let table = dialect.quote_ident(&spec.table)?;

    let col_lines: Result<Vec<String>, String> = spec.columns.iter()
        .map(|col| Ok(format!("  {}", render_column_def(col, dialect)?)))
        .collect();

    let if_not_exists = if spec.if_not_exists { "IF NOT EXISTS " } else { "" };
    let mut stmts = vec![format!(
        "CREATE TABLE {}{} (\n{}\n);",
        if_not_exists,
        table,
        col_lines?.join(",\n")
    )];

    for idx in &spec.indexes {
        stmts.push(compile_create_index(&CreateIndexSpec {
            table: spec.table.clone(),
            name: idx.name.clone(),
            columns: idx.columns.clone(),
            unique: idx.unique,
        }, dialect)?);
    }
    Ok(stmts)
}

pub fn compile_drop_table(spec: &DropTableSpec, dialect: Dialect) -> Result<String, String> {
    let table = dialect.quote_ident(&spec.table)?;
    let if_exists = if spec.if_exists { "IF EXISTS " } else { "" };
    // CASCADE is Postgres-only: SQLite errors on the keyword and MySQL ignores it.
    let cascade = if spec.cascade && dialect == Dialect::Postgres {
        " CASCADE"
    } else {
        ""
    };
    Ok(format!("DROP TABLE {}{}{};", if_exists, table, cascade))
}

pub fn compile_create_index(spec: &CreateIndexSpec, dialect: Dialect) -> Result<String, String> {
    let unique = if spec.unique { "UNIQUE " } else { "" };
    let name = dialect.quote_ident(&spec.name)?;
    let table = dialect.quote_ident(&spec.table)?;
    let cols: Result<Vec<String>, String> = spec.columns.iter().map(|c| dialect.quote_ident(c)).collect();
    Ok(format!("CREATE {}INDEX {} ON {} ({});", unique, name, table, cols?.join(", ")))
}

pub fn compile_drop_index(spec: &DropIndexSpec, dialect: Dialect) -> Result<String, String> {
    let name = dialect.quote_ident(&spec.name)?;
    let if_exists = if spec.if_exists { "IF EXISTS " } else { "" };
    Ok(format!("DROP INDEX {}{};", if_exists, name))
}

/// One column-level ALTER TABLE operation. Tagged union — TypeScript sends
/// `{ op: "addColumn", column: {...} }` etc.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "camelCase")]
pub enum AlterOp {
    AddColumn { column: ColumnDef },
    DropColumn { name: String },
    RenameColumn { from: String, to: String },
    /// Change a column's type / nullability. Postgres + MySQL only — SQLite
    /// cannot alter a column in place (the table must be recreated).
    ///
    /// `set_nullable` is tri-state on purpose: `None` leaves the existing
    /// nullability untouched, so a bare type change never silently adds or
    /// drops a NOT NULL constraint just because `ColumnDef.nullable` defaults
    /// to `false`. Only an explicit `.nullable()` / `.notNullable()` before
    /// `.alter()` sets it.
    // `rename_all` on the enum renames the VARIANTS, not their fields — a
    // multi-word field needs its own attribute or it silently stays snake_case
    // and `serde(default)` swallows the camelCase key TypeScript actually sends.
    #[serde(rename_all = "camelCase")]
    AlterColumn {
        column: ColumnDef,
        #[serde(default)]
        set_nullable: Option<bool>,
    },
    /// Toggle NOT NULL without restating the column type (Lucid/Knex
    /// `setNullable` / `dropNullable`). Postgres-only: MySQL's `MODIFY COLUMN`
    /// requires the full type, and SQLite cannot alter a column in place.
    SetNullable { name: String, nullable: bool },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AlterTableSpec {
    pub table: String,
    pub operations: Vec<AlterOp>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RenameTableSpec {
    pub table: String,
    pub to: String,
}

/// Compile ALTER TABLE → SQL statements, in call order. One operation can emit
/// more than one statement (Postgres splits a type change and a nullability
/// change into two `ALTER COLUMN` clauses), so results are flattened.
pub fn compile_alter_table(spec: &AlterTableSpec, dialect: Dialect) -> Result<Vec<String>, String> {
    if spec.operations.is_empty() {
        return Err("ALTER TABLE requires at least one operation".into());
    }
    let table = dialect.quote_ident(&spec.table)?;
    let per_op: Result<Vec<Vec<String>>, String> = spec.operations.iter().map(|op| match op {
        AlterOp::AddColumn { column } => Ok(vec![format!(
            "ALTER TABLE {} ADD COLUMN {};",
            table,
            render_column_def(column, dialect)?
        )]),
        AlterOp::DropColumn { name } => Ok(vec![format!(
            "ALTER TABLE {} DROP COLUMN {};",
            table,
            dialect.quote_ident(name)?
        )]),
        AlterOp::RenameColumn { from, to } => Ok(vec![format!(
            "ALTER TABLE {} RENAME COLUMN {} TO {};",
            table,
            dialect.quote_ident(from)?,
            dialect.quote_ident(to)?
        )]),
        AlterOp::AlterColumn { column, set_nullable } => match dialect {
            // Postgres: the physical type and the NOT NULL constraint are two
            // separate clauses. Nullability moves only when `set_nullable` says
            // so — see the `AlterOp::AlterColumn` docs for why it's tri-state.
            Dialect::Postgres => {
                let name = dialect.quote_ident(&column.name)?;
                let mut stmts = vec![format!(
                    "ALTER TABLE {} ALTER COLUMN {} TYPE {};",
                    table,
                    name,
                    dialect.map_column_type(&column.type_spec)?
                )];
                if let Some(nullable) = set_nullable {
                    stmts.push(nullability_stmt(&table, &name, *nullable));
                }
                Ok(stmts)
            }
            // MySQL rewrites the full column definition, so nullability rides
            // along inside `render_column_def` via `ColumnDef.nullable`. An
            // explicit `set_nullable` overrides it; otherwise the rendered
            // default (NOT NULL) would be a silent constraint change.
            Dialect::Mysql => {
                let mut col = column.clone();
                if let Some(nullable) = set_nullable {
                    col.nullable = *nullable;
                }
                Ok(vec![format!(
                    "ALTER TABLE {} MODIFY COLUMN {};",
                    table,
                    render_column_def(&col, dialect)?
                )])
            }
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot ALTER COLUMN in place — recreate the table instead".into(),
            ),
        },
        AlterOp::SetNullable { name, nullable } => match dialect {
            Dialect::Postgres => Ok(vec![nullability_stmt(
                &table,
                &dialect.quote_ident(name)?,
                *nullable,
            )]),
            Dialect::Mysql => Err(format!(
                "E_UNSUPPORTED: MySQL cannot toggle NOT NULL without restating the column type — use `table.<type>('{}').{}().alter()` instead",
                name,
                if *nullable { "nullable" } else { "notNullable" }
            )),
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot ALTER COLUMN in place — recreate the table instead".into(),
            ),
        },
    }).collect();
    Ok(per_op?.into_iter().flatten().collect())
}

/// Postgres `SET`/`DROP NOT NULL` clause. Both identifiers must already be quoted.
fn nullability_stmt(table: &str, column: &str, nullable: bool) -> String {
    format!(
        "ALTER TABLE {} ALTER COLUMN {} {} NOT NULL;",
        table,
        column,
        if nullable { "DROP" } else { "SET" }
    )
}

/// Compile RENAME TABLE — `ALTER TABLE old RENAME TO new` (portable across all three dialects).
pub fn compile_rename_table(spec: &RenameTableSpec, dialect: Dialect) -> Result<String, String> {
    Ok(format!(
        "ALTER TABLE {} RENAME TO {};",
        dialect.quote_ident(&spec.table)?,
        dialect.quote_ident(&spec.to)?
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dialect::ColumnTypeKind;

    fn col(name: &str, kind: ColumnTypeKind) -> ColumnDef {
        ColumnDef {
            name: name.into(),
            type_spec: ColumnTypeSpec { kind, length: None, precision: None, scale: None, values: None, raw_type: None },
            nullable: true,
            primary: false,
            auto_increment: false,
            unique: false,
            unsigned: false,
            default: None,
            references: None,
        }
    }

    #[test]
    fn create_table_sqlite() {
        let spec = CreateTableSpec {
            table: "users".into(),
            columns: vec![
                ColumnDef { primary: true, nullable: false, ..col("id", ColumnTypeKind::Integer) },
                ColumnDef { nullable: false, ..col("name", ColumnTypeKind::String) },
            ],
            indexes: vec![],
            if_not_exists: false,
        };
        let stmts = compile_create_table(&spec, Dialect::Sqlite).unwrap();
        assert_eq!(stmts.len(), 1);
        assert!(stmts[0].contains("CREATE TABLE \"users\""));
        assert!(stmts[0].contains("\"id\" INTEGER PRIMARY KEY NOT NULL"));
        assert!(stmts[0].contains("\"name\" TEXT NOT NULL"));
    }

    #[test]
    fn auto_increment_per_dialect() {
        let make = || CreateTableSpec {
            table: "ream_migrations".into(),
            columns: vec![
                ColumnDef { auto_increment: true, nullable: false, ..col("id", ColumnTypeKind::Integer) },
                ColumnDef { nullable: false, unique: true, ..col("name", ColumnTypeKind::String) },
            ],
            indexes: vec![],
            if_not_exists: true,
        };
        let sqlite = compile_create_table(&make(), Dialect::Sqlite).unwrap();
        assert!(sqlite[0].contains("\"id\" INTEGER PRIMARY KEY AUTOINCREMENT"));
        let pg = compile_create_table(&make(), Dialect::Postgres).unwrap();
        assert!(pg[0].contains("\"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"));
        let my = compile_create_table(&make(), Dialect::Mysql).unwrap();
        assert!(my[0].contains("`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY"));
    }

    #[test]
    fn big_increments_widens_to_64bit() {
        let make = || CreateTableSpec {
            table: "events".into(),
            columns: vec![ColumnDef {
                auto_increment: true,
                nullable: false,
                ..col("id", ColumnTypeKind::BigInteger)
            }],
            indexes: vec![],
            if_not_exists: false,
        };
        assert!(compile_create_table(&make(), Dialect::Postgres).unwrap()[0]
            .contains("BIGINT GENERATED BY DEFAULT AS IDENTITY"));
        assert!(compile_create_table(&make(), Dialect::Mysql).unwrap()[0]
            .contains("BIGINT NOT NULL AUTO_INCREMENT"));
    }

    #[test]
    fn create_table_postgres_varchar() {
        let spec = CreateTableSpec {
            table: "users".into(),
            columns: vec![ColumnDef {
                nullable: false,
                type_spec: ColumnTypeSpec { kind: ColumnTypeKind::String, length: Some(100), precision: None, scale: None, values: None, raw_type: None },
                ..col("email", ColumnTypeKind::String)
            }],
            indexes: vec![],
            if_not_exists: false,
        };
        let stmts = compile_create_table(&spec, Dialect::Postgres).unwrap();
        assert!(stmts[0].contains("\"email\" VARCHAR(100) NOT NULL"));
    }

    #[test]
    fn create_table_with_fk_and_index() {
        let spec = CreateTableSpec {
            table: "orders".into(),
            columns: vec![
                ColumnDef { primary: true, nullable: false, ..col("id", ColumnTypeKind::Integer) },
                ColumnDef {
                    nullable: false,
                    references: Some(ForeignKeyRef { table: "users".into(), column: "id".into(), on_delete: None, on_update: None }),
                    ..col("user_id", ColumnTypeKind::Integer)
                },
            ],
            indexes: vec![IndexDef { name: "idx_orders_user".into(), columns: vec!["user_id".into()], unique: false }],
            if_not_exists: false,
        };
        let stmts = compile_create_table(&spec, Dialect::Sqlite).unwrap();
        assert_eq!(stmts.len(), 2);
        assert!(stmts[0].contains("REFERENCES \"users\"(\"id\")"));
        assert_eq!(stmts[1], "CREATE INDEX \"idx_orders_user\" ON \"orders\" (\"user_id\");");
    }

    #[test]
    fn fk_referential_actions() {
        let spec = CreateTableSpec {
            table: "orders".into(),
            columns: vec![ColumnDef {
                nullable: false,
                references: Some(ForeignKeyRef {
                    table: "users".into(),
                    column: "id".into(),
                    on_delete: Some("cascade".into()),
                    on_update: Some("set null".into()),
                }),
                ..col("user_id", ColumnTypeKind::Integer)
            }],
            indexes: vec![],
            if_not_exists: false,
        };
        let stmts = compile_create_table(&spec, Dialect::Postgres).unwrap();
        assert!(stmts[0].contains("REFERENCES \"users\"(\"id\") ON DELETE CASCADE ON UPDATE SET NULL"), "sql: {}", stmts[0]);
    }

    #[test]
    fn fk_rejects_bad_action() {
        let spec = CreateTableSpec {
            table: "orders".into(),
            columns: vec![ColumnDef {
                references: Some(ForeignKeyRef {
                    table: "users".into(), column: "id".into(),
                    on_delete: Some("DROP TABLE".into()), on_update: None,
                }),
                ..col("user_id", ColumnTypeKind::Integer)
            }],
            indexes: vec![],
            if_not_exists: false,
        };
        assert!(compile_create_table(&spec, Dialect::Sqlite).is_err());
    }

    #[test]
    fn alter_table_add_drop_rename() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![
                AlterOp::AddColumn { column: ColumnDef { nullable: false, ..col("age", ColumnTypeKind::Integer) } },
                AlterOp::DropColumn { name: "legacy".into() },
                AlterOp::RenameColumn { from: "name".into(), to: "full_name".into() },
            ],
        };
        let stmts = compile_alter_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(stmts.len(), 3);
        assert_eq!(stmts[0], "ALTER TABLE \"users\" ADD COLUMN \"age\" INTEGER NOT NULL;");
        assert_eq!(stmts[1], "ALTER TABLE \"users\" DROP COLUMN \"legacy\";");
        assert_eq!(stmts[2], "ALTER TABLE \"users\" RENAME COLUMN \"name\" TO \"full_name\";");
    }

    #[test]
    fn alter_column_per_dialect() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::AlterColumn {
                column: ColumnDef {
                    type_spec: ColumnTypeSpec { kind: ColumnTypeKind::String, length: Some(120), precision: None, scale: None, values: None, raw_type: None },
                    ..col("email", ColumnTypeKind::String)
                },
                set_nullable: None,
            }],
        };
        assert_eq!(
            compile_alter_table(&spec, Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"users\" ALTER COLUMN \"email\" TYPE VARCHAR(120);"
        );
        assert!(compile_alter_table(&spec, Dialect::Mysql).unwrap()[0]
            .starts_with("ALTER TABLE `users` MODIFY COLUMN `email` VARCHAR(120)"));
        assert!(compile_alter_table(&spec, Dialect::Sqlite).is_err());
    }

    /// A bare type change must not touch NOT NULL: `ColumnDef.nullable`
    /// defaults to false, so without the tri-state it would silently add one.
    #[test]
    fn alter_column_leaves_nullability_alone_by_default() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::AlterColumn {
                column: ColumnDef { nullable: false, ..col("email", ColumnTypeKind::Text) },
                set_nullable: None,
            }],
        };
        let pg = compile_alter_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(pg.len(), 1);
        assert!(!pg[0].contains("NOT NULL"));
    }

    #[test]
    fn alter_column_applies_explicit_nullability() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::AlterColumn {
                column: col("email", ColumnTypeKind::Text),
                set_nullable: Some(false),
            }],
        };
        let pg = compile_alter_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(pg.len(), 2);
        assert_eq!(pg[0], "ALTER TABLE \"users\" ALTER COLUMN \"email\" TYPE TEXT;");
        assert_eq!(pg[1], "ALTER TABLE \"users\" ALTER COLUMN \"email\" SET NOT NULL;");
        // MySQL folds nullability into the restated definition.
        let my = compile_alter_table(&spec, Dialect::Mysql).unwrap();
        assert_eq!(my.len(), 1);
        assert!(my[0].contains("NOT NULL"));
    }

    #[test]
    fn set_nullable_is_postgres_only() {
        let spec = |nullable| AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::SetNullable { name: "email".into(), nullable }],
        };
        assert_eq!(
            compile_alter_table(&spec(true), Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"users\" ALTER COLUMN \"email\" DROP NOT NULL;"
        );
        assert_eq!(
            compile_alter_table(&spec(false), Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"users\" ALTER COLUMN \"email\" SET NOT NULL;"
        );
        // MySQL needs the type restated; the error must say so.
        let err = compile_alter_table(&spec(true), Dialect::Mysql).unwrap_err();
        assert!(err.contains("E_UNSUPPORTED"), "{err}");
        assert!(err.contains(".alter()"), "{err}");
        assert!(compile_alter_table(&spec(true), Dialect::Sqlite).is_err());
    }

    #[test]
    fn alter_table_rejects_injected_identifiers() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::DropColumn { name: "x\"; DROP TABLE users; --".into() }],
        };
        assert!(compile_alter_table(&spec, Dialect::Postgres).is_err());
    }

    /// Wire-contract guard: TypeScript sends `setNullable` (camelCase). With
    /// only the enum-level `rename_all`, serde looks for `set_nullable`, finds
    /// nothing, and `serde(default)` quietly yields `None` — the nullability
    /// change vanishes with no error. Assert the camelCase key is honoured.
    #[test]
    fn alter_column_deserialises_camel_case_set_nullable() {
        let json = r#"{
            "table": "users",
            "operations": [
                { "op": "alterColumn", "setNullable": false,
                  "column": { "name": "email", "kind": "text", "nullable": true } }
            ]
        }"#;
        let spec: AlterTableSpec = serde_json::from_str(json).unwrap();
        let stmts = compile_alter_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(stmts.len(), 2, "setNullable was dropped on the wire: {stmts:?}");
        assert_eq!(stmts[1], "ALTER TABLE \"users\" ALTER COLUMN \"email\" SET NOT NULL;");
    }

    #[test]
    fn alter_table_rejects_empty_operations() {
        let spec = AlterTableSpec { table: "users".into(), operations: vec![] };
        assert!(compile_alter_table(&spec, Dialect::Postgres).is_err());
    }

    #[test]
    fn rename_table_portable() {
        let spec = RenameTableSpec { table: "old".into(), to: "new".into() };
        assert_eq!(compile_rename_table(&spec, Dialect::Sqlite).unwrap(), "ALTER TABLE \"old\" RENAME TO \"new\";");
        assert_eq!(compile_rename_table(&spec, Dialect::Mysql).unwrap(), "ALTER TABLE `old` RENAME TO `new`;");
    }

    #[test]
    fn drop_table() {
        let spec = DropTableSpec { table: "old".into(), if_exists: true, cascade: false };
        assert_eq!(compile_drop_table(&spec, Dialect::Sqlite).unwrap(), "DROP TABLE IF EXISTS \"old\";");
    }

    #[test]
    fn drop_table_cascade_postgres_only() {
        // CASCADE renders on Postgres…
        let pg = DropTableSpec { table: "old".into(), if_exists: true, cascade: true };
        assert_eq!(
            compile_drop_table(&pg, Dialect::Postgres).unwrap(),
            "DROP TABLE IF EXISTS \"old\" CASCADE;"
        );
        // …but is suppressed on SQLite (keyword unsupported) and MySQL (no-op).
        let sqlite = DropTableSpec { table: "old".into(), if_exists: false, cascade: true };
        assert_eq!(compile_drop_table(&sqlite, Dialect::Sqlite).unwrap(), "DROP TABLE \"old\";");
        let mysql = DropTableSpec { table: "old".into(), if_exists: false, cascade: true };
        assert_eq!(compile_drop_table(&mysql, Dialect::Mysql).unwrap(), "DROP TABLE `old`;");
    }

    #[test]
    fn enum_mysql_native_pg_sqlite_check() {
        let mut c = col("status", ColumnTypeKind::Enum);
        c.type_spec.values = Some(vec!["active".into(), "inactive".into()]);
        c.nullable = false;
        let spec = CreateTableSpec {
            table: "t".into(), columns: vec![c], indexes: vec![], if_not_exists: false,
        };
        // MySQL renders a native ENUM.
        assert!(compile_create_table(&spec, Dialect::Mysql).unwrap()[0]
            .contains("ENUM('active', 'inactive')"));
        // Postgres/SQLite render TEXT + a CHECK pinning the value set.
        let pg = compile_create_table(&spec, Dialect::Postgres).unwrap()[0].clone();
        assert!(pg.contains("\"status\" TEXT"), "sql: {}", pg);
        assert!(
            pg.contains("CHECK (\"status\" IN ('active', 'inactive'))"),
            "sql: {}", pg
        );
    }

    #[test]
    fn enum_escapes_quotes_and_rejects_empty() {
        // A single quote in a value is doubled, not left to break out of the literal.
        let mut c = col("s", ColumnTypeKind::Enum);
        c.type_spec.values = Some(vec!["O'Brien".into()]);
        let spec = CreateTableSpec {
            table: "t".into(), columns: vec![c], indexes: vec![], if_not_exists: false,
        };
        assert!(compile_create_table(&spec, Dialect::Sqlite).unwrap()[0].contains("'O''Brien'"));
        // An empty value set is rejected rather than emitting `ENUM()` / `IN ()`.
        let mut e = col("s", ColumnTypeKind::Enum);
        e.type_spec.values = Some(vec![]);
        let espec = CreateTableSpec {
            table: "t".into(), columns: vec![e], indexes: vec![], if_not_exists: false,
        };
        assert!(compile_create_table(&espec, Dialect::Sqlite).is_err());
    }

    #[test]
    fn unsigned_is_mysql_only() {
        let mut c = col("n", ColumnTypeKind::Integer);
        c.unsigned = true;
        let spec = CreateTableSpec {
            table: "t".into(), columns: vec![c], indexes: vec![], if_not_exists: false,
        };
        assert!(compile_create_table(&spec, Dialect::Mysql).unwrap()[0].contains("INT UNSIGNED"));
        // pg/sqlite have no unsigned integers — the modifier is dropped.
        assert!(!compile_create_table(&spec, Dialect::Postgres).unwrap()[0].contains("UNSIGNED"));
        assert!(!compile_create_table(&spec, Dialect::Sqlite).unwrap()[0].contains("UNSIGNED"));
    }

    #[test]
    fn foreign_key_on_delete_on_update_render() {
        let mut c = col("author_id", ColumnTypeKind::Integer);
        c.references = Some(ForeignKeyRef {
            table: "users".into(),
            column: "id".into(),
            on_delete: Some("cascade".into()),
            on_update: Some("restrict".into()),
        });
        let spec = CreateTableSpec {
            table: "posts".into(), columns: vec![c], indexes: vec![], if_not_exists: false,
        };
        let sql = compile_create_table(&spec, Dialect::Postgres).unwrap()[0].clone();
        assert!(
            sql.contains("REFERENCES \"users\"(\"id\") ON DELETE CASCADE ON UPDATE RESTRICT"),
            "sql: {}", sql
        );
    }

    #[test]
    fn create_index_unique() {
        let spec = CreateIndexSpec {
            table: "users".into(),
            name: "idx_users_email".into(),
            columns: vec!["email".into()],
            unique: true,
        };
        assert_eq!(
            compile_create_index(&spec, Dialect::Sqlite).unwrap(),
            "CREATE UNIQUE INDEX \"idx_users_email\" ON \"users\" (\"email\");"
        );
    }

    #[test]
    fn mysql_backticks_in_ddl() {
        let spec = DropTableSpec { table: "old".into(), if_exists: false, cascade: false };
        assert_eq!(compile_drop_table(&spec, Dialect::Mysql).unwrap(), "DROP TABLE `old`;");
    }

    #[test]
    fn rejects_injection_in_table_name() {
        let spec = DropTableSpec { table: "users; DROP TABLE admins--".into(), if_exists: false, cascade: false };
        assert!(compile_drop_table(&spec, Dialect::Sqlite).is_err());
    }
}
