//! DDL compilers: CREATE TABLE, DROP TABLE, CREATE INDEX, DROP INDEX.
//!
//! DDL statements don't bind params — they return plain SQL strings.

use crate::dialect::{ColumnTypeKind, ColumnTypeSpec, Dialect};
use serde::{Deserialize, Serialize};

/// Quote a value as a SQL string literal (`'x'`), doubling embedded single
/// quotes. Rejects NUL — no dialect accepts it inside a literal and it can
/// truncate the statement. Used for `ENUM(...)` / `CHECK (… IN (…))` values.
fn quote_str_literal(s: &str) -> Result<String, String> {
    if s.contains('\0') {
        return Err(format!(
            "E_UNSAFE_LITERAL: enum value contains a NUL byte: {:?}",
            s
        ));
    }
    Ok(format!("'{}'", s.replace('\'', "''")))
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateTableSpec {
    pub table: String,
    pub columns: Vec<ColumnDef>,
    #[serde(default)]
    pub indexes: Vec<IndexDef>,
    #[serde(default)]
    pub if_not_exists: bool,
    /// Table-level constraints (composite PK/unique/FK and CHECKs).
    #[serde(default)]
    pub constraints: Vec<TableConstraint>,
    #[serde(default)]
    pub options: TableOptions,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ColumnDef {
    pub name: String,
    #[serde(flatten)]
    pub type_spec: ColumnTypeSpec,
    #[serde(default)]
    pub nullable: bool,
    #[serde(default)]
    pub primary: bool,
    /// Dialect-appropriate auto-increment / identity column (Lucid `increments()`):
    /// SQLite `INTEGER PRIMARY KEY AUTOINCREMENT`, Postgres `GENERATED BY DEFAULT
    /// AS IDENTITY`, MySQL `AUTO_INCREMENT`. Implies PRIMARY KEY.
    #[serde(default)]
    pub auto_increment: bool,
    #[serde(default)]
    pub unique: bool,
    /// MySQL `UNSIGNED` numeric modifier (Lucid `unsigned()`). Ignored on
    /// Postgres and SQLite, which have no unsigned integer types.
    #[serde(default)]
    pub unsigned: bool,
    #[serde(default)]
    pub default: Option<String>,
    #[serde(default)]
    pub references: Option<ForeignKeyRef>,
    /// Column comment (Lucid/Knex `comment()`). MySQL renders it inline;
    /// Postgres needs a separate `COMMENT ON COLUMN` statement (emitted by the
    /// caller); SQLite has no column comments and drops it.
    #[serde(default)]
    pub comment: Option<String>,
    /// Column collation (Lucid/Knex `collate()`), e.g. `utf8mb4_unicode_ci`.
    /// Validated as an identifier — it is interpolated, not bound.
    #[serde(default)]
    pub collate: Option<String>,
    /// Position of a newly added column (Lucid/Knex `first()` / `after(col)`).
    /// MySQL-only: Postgres and SQLite always append and reject the clause.
    #[serde(default)]
    pub position: Option<ColumnPosition>,
}

/// Where to place a column being added (MySQL `FIRST` / `AFTER col`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "at", rename_all = "camelCase")]
pub enum ColumnPosition {
    First,
    After { column: String },
}

/// Storage options for `CREATE TABLE` (Lucid/Knex `engine`/`charset`/`collate`/`comment`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TableOptions {
    /// MySQL storage engine (`InnoDB`). Ignored on pg/sqlite.
    #[serde(default)]
    pub engine: Option<String>,
    /// MySQL default charset. Ignored on pg/sqlite.
    #[serde(default)]
    pub charset: Option<String>,
    /// MySQL default collation. Ignored on pg/sqlite.
    #[serde(default)]
    pub collate: Option<String>,
    /// Table comment. Inline on MySQL, a separate `COMMENT ON TABLE` on
    /// Postgres, dropped on SQLite.
    #[serde(default)]
    pub comment: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ForeignKeyRef {
    pub table: String,
    pub column: String,
    /// Referential action for `ON DELETE` (CASCADE / SET NULL / RESTRICT / NO ACTION / SET DEFAULT).
    #[serde(default)]
    pub on_delete: Option<String>,
    /// Referential action for `ON UPDATE`.
    #[serde(default)]
    pub on_update: Option<String>,
}

/// Validate + normalise a referential action against the SQL-standard allow-list.
/// Case-insensitive; returns the canonical upper-cased keyword.
fn referential_action(action: &str) -> Result<&'static str, String> {
    match action.to_uppercase().replace('_', " ").as_str() {
        "CASCADE" => Ok("CASCADE"),
        "SET NULL" => Ok("SET NULL"),
        "SET DEFAULT" => Ok("SET DEFAULT"),
        "RESTRICT" => Ok("RESTRICT"),
        "NO ACTION" => Ok("NO ACTION"),
        _ => Err(format!(
            "E_UNSAFE_SQL: invalid referential action '{}' (use CASCADE, SET NULL, SET DEFAULT, RESTRICT, or NO ACTION)",
            action
        )),
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IndexDef {
    pub name: String,
    pub columns: Vec<String>,
    #[serde(default)]
    pub unique: bool,
}

/// Render a JSON scalar as a SQL literal for a CHECK constraint. DDL cannot
/// bind parameters, so every value here is interpolated — strings go through
/// [`quote_str_literal`] and anything that isn't a scalar is rejected rather
/// than stringified into something that might parse as SQL.
fn render_scalar_literal(v: &serde_json::Value, dialect: Dialect) -> Result<String, String> {
    match v {
        serde_json::Value::String(s) => quote_str_literal(s),
        // `serde_json` already parsed this as a number — it cannot carry SQL.
        serde_json::Value::Number(n) => Ok(n.to_string()),
        serde_json::Value::Bool(b) => Ok(match dialect {
            Dialect::Postgres => if *b { "TRUE".into() } else { "FALSE".into() },
            // SQLite and MySQL have no boolean literal — they store 1/0.
            _ => if *b { "1".to_string() } else { "0".to_string() },
        }),
        serde_json::Value::Null => Ok("NULL".into()),
        _ => Err(format!(
            "E_UNSAFE_LITERAL: a check constraint value must be a string, number, boolean or null — got {v}"
        )),
    }
}

/// Validate a comparison operator against the SQL-standard allow-list
/// (Lucid/Knex `checkLength(operator, …)`). Interpolated, so never free-form.
fn comparison_operator(op: &str) -> Result<&'static str, String> {
    match op.trim() {
        "=" => Ok("="),
        "!=" | "<>" => Ok("<>"),
        "<" => Ok("<"),
        "<=" => Ok("<="),
        ">" => Ok(">"),
        ">=" => Ok(">="),
        _ => Err(format!(
            "E_UNSAFE_SQL: invalid comparison operator '{op}' (use =, !=, <>, <, <=, > or >=)"
        )),
    }
}

/// A CHECK predicate. Structured rather than free-form SQL: each variant is
/// safe by construction, which is what lets a migration express the common
/// constraints without opening a SQL hole. `Raw` is the escape hatch and is
/// exactly as trusted as `schema.raw()`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "check", rename_all = "camelCase")]
pub enum CheckExpr {
    Positive { column: String },
    Negative { column: String },
    In { column: String, values: Vec<serde_json::Value> },
    NotIn { column: String, values: Vec<serde_json::Value> },
    /// One or more `BETWEEN lo AND hi` intervals, OR'd together (Knex semantics).
    Between { column: String, ranges: Vec<Vec<serde_json::Value>> },
    Length { column: String, operator: String, length: i64 },
    Regex { column: String, pattern: String },
    Raw { predicate: String },
}

fn render_check_expr(expr: &CheckExpr, dialect: Dialect) -> Result<String, String> {
    let literals = |vals: &[serde_json::Value]| -> Result<String, String> {
        if vals.is_empty() {
            return Err("E_CHECK_EMPTY: a check constraint requires at least one value".into());
        }
        Ok(vals
            .iter()
            .map(|v| render_scalar_literal(v, dialect))
            .collect::<Result<Vec<_>, _>>()?
            .join(", "))
    };

    Ok(match expr {
        CheckExpr::Positive { column } => format!("{} > 0", dialect.quote_ident(column)?),
        CheckExpr::Negative { column } => format!("{} < 0", dialect.quote_ident(column)?),
        CheckExpr::In { column, values } => {
            format!("{} IN ({})", dialect.quote_ident(column)?, literals(values)?)
        }
        CheckExpr::NotIn { column, values } => {
            format!("{} NOT IN ({})", dialect.quote_ident(column)?, literals(values)?)
        }
        CheckExpr::Between { column, ranges } => {
            if ranges.is_empty() {
                return Err("E_CHECK_EMPTY: checkBetween requires at least one interval".into());
            }
            let col = dialect.quote_ident(column)?;
            let clauses = ranges
                .iter()
                .map(|r| {
                    if r.len() != 2 {
                        return Err(format!(
                            "E_CHECK_RANGE: checkBetween expects [min, max] intervals — got {} value(s)",
                            r.len()
                        ));
                    }
                    Ok(format!(
                        "{} BETWEEN {} AND {}",
                        col,
                        render_scalar_literal(&r[0], dialect)?,
                        render_scalar_literal(&r[1], dialect)?
                    ))
                })
                .collect::<Result<Vec<_>, String>>()?;
            clauses.join(" OR ")
        }
        CheckExpr::Length { column, operator, length } => format!(
            "LENGTH({}) {} {}",
            dialect.quote_ident(column)?,
            comparison_operator(operator)?,
            length
        ),
        // Postgres spells regex match `~`; SQLite and MySQL use `REGEXP`.
        // SQLite parses REGEXP but ships no implementation — the constraint
        // only works if the connection registers a `regexp` function. Knex has
        // the same behaviour, so emitting it is parity, not a new footgun.
        CheckExpr::Regex { column, pattern } => format!(
            "{} {} {}",
            dialect.quote_ident(column)?,
            if dialect == Dialect::Postgres { "~" } else { "REGEXP" },
            quote_str_literal(pattern)?
        ),
        CheckExpr::Raw { predicate } => predicate.clone(),
    })
}

/// A multi-column foreign key target (Lucid/Knex `foreign([...]).references([...]).inTable(…)`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ForeignKeyRefMulti {
    pub table: String,
    pub columns: Vec<String>,
    #[serde(default)]
    pub on_delete: Option<String>,
    #[serde(default)]
    pub on_update: Option<String>,
}

/// A table-level constraint (composite keys and CHECKs).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "constraint", rename_all = "camelCase")]
pub enum TableConstraint {
    Primary { #[serde(default)] name: Option<String>, columns: Vec<String> },
    Unique { #[serde(default)] name: Option<String>, columns: Vec<String> },
    Foreign {
        #[serde(default)]
        name: Option<String>,
        columns: Vec<String>,
        references: ForeignKeyRefMulti,
    },
    Check { #[serde(default)] name: Option<String>, expr: CheckExpr },
}

/// Render `[CONSTRAINT "name"] <body>` for a table-level constraint.
fn render_table_constraint(c: &TableConstraint, dialect: Dialect) -> Result<String, String> {
    let cols = |columns: &[String]| -> Result<String, String> {
        if columns.is_empty() {
            return Err("E_CONSTRAINT_EMPTY: a constraint requires at least one column".into());
        }
        Ok(columns
            .iter()
            .map(|c| dialect.quote_ident(c))
            .collect::<Result<Vec<_>, _>>()?
            .join(", "))
    };
    let named = |name: &Option<String>, body: String| -> Result<String, String> {
        Ok(match name {
            Some(n) => format!("CONSTRAINT {} {}", dialect.quote_ident(n)?, body),
            None => body,
        })
    };

    match c {
        TableConstraint::Primary { name, columns } => {
            named(name, format!("PRIMARY KEY ({})", cols(columns)?))
        }
        TableConstraint::Unique { name, columns } => {
            named(name, format!("UNIQUE ({})", cols(columns)?))
        }
        TableConstraint::Foreign { name, columns, references } => {
            let mut body = format!(
                "FOREIGN KEY ({}) REFERENCES {} ({})",
                cols(columns)?,
                dialect.quote_ident(&references.table)?,
                cols(&references.columns)?
            );
            if let Some(action) = &references.on_delete {
                body.push_str(&format!(" ON DELETE {}", referential_action(action)?));
            }
            if let Some(action) = &references.on_update {
                body.push_str(&format!(" ON UPDATE {}", referential_action(action)?));
            }
            named(name, body)
        }
        TableConstraint::Check { name, expr } => {
            named(name, format!("CHECK ({})", render_check_expr(expr, dialect)?))
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DropTableSpec {
    pub table: String,
    #[serde(default)]
    pub if_exists: bool,
    /// Emit `CASCADE` so dependent foreign keys drop with the table. Honoured
    /// only on Postgres — SQLite rejects the keyword and MySQL treats it as a
    /// no-op (it relies on `SET FOREIGN_KEY_CHECKS = 0` instead).
    #[serde(default)]
    pub cascade: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateSchemaSpec {
    pub name: String,
    #[serde(default)]
    pub if_not_exists: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DropSchemaSpec {
    pub name: String,
    #[serde(default)]
    pub if_exists: bool,
    /// `CASCADE` — Postgres-only (drops objects in the schema).
    #[serde(default)]
    pub cascade: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateTableLikeSpec {
    /// The new table to create.
    pub table: String,
    /// The existing table to copy the structure from.
    pub like_table: String,
    #[serde(default)]
    pub if_not_exists: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateIndexSpec {
    pub table: String,
    pub name: String,
    pub columns: Vec<String>,
    #[serde(default)]
    pub unique: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DropIndexSpec {
    pub name: String,
    #[serde(default)]
    pub if_exists: bool,
}

/// Render a single column definition (`"name" TYPE [PRIMARY KEY] [NOT NULL] …
/// [REFERENCES …]`) — shared by CREATE TABLE and ALTER TABLE ADD/ALTER COLUMN.
fn render_column_def(col: &ColumnDef, dialect: Dialect) -> Result<String, String> {
    let mut parts: Vec<String> = vec![dialect.quote_ident(&col.name)?];
    if col.auto_increment {
        // Type + PRIMARY KEY + identity are one dialect-specific clause;
        // NOT NULL / UNIQUE / DEFAULT are subsumed by the identity column.
        parts.push(dialect.auto_increment_column(col.type_spec.kind));
    } else {
        if col.type_spec.kind == ColumnTypeKind::Enum {
            // MySQL has a native ENUM(...); pg/sqlite render TEXT + a CHECK that
            // pins the value set (Lucid's non-native enum behaviour).
            let values = col.type_spec.values.as_deref().unwrap_or(&[]);
            if values.is_empty() {
                return Err("E_ENUM_EMPTY: an enum column requires at least one value".into());
            }
            let literals = values
                .iter()
                .map(|v| quote_str_literal(v))
                .collect::<Result<Vec<_>, _>>()?
                .join(", ");
            match dialect {
                Dialect::Mysql => parts.push(format!("ENUM({})", literals)),
                _ => {
                    parts.push("TEXT".into());
                    parts.push(format!(
                        "CHECK ({} IN ({}))",
                        dialect.quote_ident(&col.name)?,
                        literals
                    ));
                }
            }
        } else {
            parts.push(dialect.map_column_type(&col.type_spec)?);
            // MySQL-only UNSIGNED modifier — directly after the numeric type.
            if col.unsigned && matches!(dialect, Dialect::Mysql) {
                parts.push("UNSIGNED".into());
            }
        }
        if col.primary { parts.push("PRIMARY KEY".into()); }
        if !col.nullable { parts.push("NOT NULL".into()); }
        if col.unique { parts.push("UNIQUE".into()); }
        if let Some(default) = &col.default {
            parts.push(dialect.wrap_default(default));
        }
    }
    // COLLATE binds to the type, so it must precede the constraints.
    if let Some(collation) = &col.collate {
        parts.push(format!("COLLATE {}", dialect.quote_ident(collation)?));
    }
    if let Some(fk) = &col.references {
        parts.push(format!(
            "REFERENCES {}({})",
            dialect.quote_ident(&fk.table)?,
            dialect.quote_ident(&fk.column)?
        ));
        if let Some(action) = &fk.on_delete {
            parts.push(format!("ON DELETE {}", referential_action(action)?));
        }
        if let Some(action) = &fk.on_update {
            parts.push(format!("ON UPDATE {}", referential_action(action)?));
        }
    }
    // Only MySQL carries a comment inside the column definition. Postgres needs
    // a separate COMMENT ON COLUMN (see `column_comment_stmts`) and SQLite has
    // no column comments at all.
    if let Some(comment) = &col.comment {
        if dialect == Dialect::Mysql {
            parts.push(format!("COMMENT {}", quote_str_literal(comment)?));
        }
    }
    Ok(parts.join(" "))
}

/// `COMMENT ON COLUMN` statements for a Postgres table — Postgres cannot carry
/// a comment inside the column definition the way MySQL does.
fn column_comment_stmts(
    table: &str,
    columns: &[ColumnDef],
    dialect: Dialect,
) -> Result<Vec<String>, String> {
    if dialect != Dialect::Postgres {
        return Ok(vec![]);
    }
    columns
        .iter()
        .filter_map(|c| c.comment.as_ref().map(|cm| (c, cm)))
        .map(|(c, comment)| {
            Ok(format!(
                "COMMENT ON COLUMN {}.{} IS {};",
                dialect.quote_ident(table)?,
                dialect.quote_ident(&c.name)?,
                quote_str_literal(comment)?
            ))
        })
        .collect()
}

/// The MySQL clause tail (`ENGINE=… DEFAULT CHARSET=… COLLATE=… COMMENT=…`)
/// appended after `CREATE TABLE (...)`. Empty on every other dialect.
fn table_options_clause(options: &TableOptions, dialect: Dialect) -> Result<String, String> {
    if dialect != Dialect::Mysql {
        return Ok(String::new());
    }
    let mut parts: Vec<String> = vec![];
    if let Some(engine) = &options.engine {
        parts.push(format!("ENGINE = {}", dialect.quote_ident(engine)?));
    }
    if let Some(charset) = &options.charset {
        parts.push(format!("DEFAULT CHARSET = {}", dialect.quote_ident(charset)?));
    }
    if let Some(collate) = &options.collate {
        parts.push(format!("COLLATE = {}", dialect.quote_ident(collate)?));
    }
    if let Some(comment) = &options.comment {
        parts.push(format!("COMMENT = {}", quote_str_literal(comment)?));
    }
    Ok(if parts.is_empty() { String::new() } else { format!(" {}", parts.join(" ")) })
}

/// Compile CREATE TABLE → one or more SQL statements (the CREATE itself + CREATE INDEX for each index).
pub fn compile_create_table(spec: &CreateTableSpec, dialect: Dialect) -> Result<Vec<String>, String> {
    if spec.columns.is_empty() {
        return Err("CREATE TABLE requires at least one column".into());
    }
    let table = dialect.quote_ident(&spec.table)?;

    let mut body: Vec<String> = spec.columns.iter()
        .map(|col| Ok(format!("  {}", render_column_def(col, dialect)?)))
        .collect::<Result<Vec<_>, String>>()?;
    // Table-level constraints sit alongside the column lines, after them.
    for c in &spec.constraints {
        body.push(format!("  {}", render_table_constraint(c, dialect)?));
    }

    let if_not_exists = if spec.if_not_exists { "IF NOT EXISTS " } else { "" };
    let mut stmts = vec![format!(
        "CREATE TABLE {}{} (\n{}\n){};",
        if_not_exists,
        table,
        body.join(",\n"),
        table_options_clause(&spec.options, dialect)?
    )];

    // Postgres carries comments as separate statements, not inline.
    stmts.extend(column_comment_stmts(&spec.table, &spec.columns, dialect)?);
    if dialect == Dialect::Postgres {
        if let Some(comment) = &spec.options.comment {
            stmts.push(format!(
                "COMMENT ON TABLE {} IS {};",
                table,
                quote_str_literal(comment)?
            ));
        }
    }

    for idx in &spec.indexes {
        stmts.push(compile_create_index(&CreateIndexSpec {
            table: spec.table.clone(),
            name: idx.name.clone(),
            columns: idx.columns.clone(),
            unique: idx.unique,
        }, dialect)?);
    }
    Ok(stmts)
}

pub fn compile_drop_table(spec: &DropTableSpec, dialect: Dialect) -> Result<String, String> {
    let table = dialect.quote_ident(&spec.table)?;
    let if_exists = if spec.if_exists { "IF EXISTS " } else { "" };
    // CASCADE is Postgres-only: SQLite errors on the keyword and MySQL ignores it.
    let cascade = if spec.cascade && dialect == Dialect::Postgres {
        " CASCADE"
    } else {
        ""
    };
    Ok(format!("DROP TABLE {}{}{};", if_exists, table, cascade))
}

/// `CREATE SCHEMA [IF NOT EXISTS] name` (Lucid/Knex `createSchema`). Postgres and
/// MySQL (where `SCHEMA` is a synonym for `DATABASE`); SQLite has no schemas.
pub fn compile_create_schema(spec: &CreateSchemaSpec, dialect: Dialect) -> Result<String, String> {
    if dialect == Dialect::Sqlite {
        return Err("E_UNSUPPORTED: SQLite has no schemas — createSchema needs Postgres or MySQL".into());
    }
    let name = dialect.quote_ident(&spec.name)?;
    let if_not_exists = if spec.if_not_exists { "IF NOT EXISTS " } else { "" };
    Ok(format!("CREATE SCHEMA {}{};", if_not_exists, name))
}

/// `DROP SCHEMA [IF EXISTS] name [CASCADE]` (Lucid/Knex `dropSchema`). CASCADE is
/// Postgres-only. SQLite has no schemas.
pub fn compile_drop_schema(spec: &DropSchemaSpec, dialect: Dialect) -> Result<String, String> {
    if dialect == Dialect::Sqlite {
        return Err("E_UNSUPPORTED: SQLite has no schemas — dropSchema needs Postgres or MySQL".into());
    }
    let name = dialect.quote_ident(&spec.name)?;
    let if_exists = if spec.if_exists { "IF EXISTS " } else { "" };
    let cascade = if spec.cascade && dialect == Dialect::Postgres {
        " CASCADE"
    } else {
        ""
    };
    Ok(format!("DROP SCHEMA {}{}{};", if_exists, name, cascade))
}

/// `CREATE TABLE new (LIKE old …)` (Lucid/Knex `createTableLike`) — copy a table's
/// structure. Postgres copies everything (`INCLUDING ALL`); MySQL uses `LIKE`;
/// SQLite has no `LIKE`, so it copies COLUMNS ONLY via `AS SELECT … WHERE 0`
/// (constraints/indexes are not carried — the same limitation Knex documents).
pub fn compile_create_table_like(
    spec: &CreateTableLikeSpec,
    dialect: Dialect,
) -> Result<String, String> {
    let table = dialect.quote_ident(&spec.table)?;
    let like = dialect.quote_ident(&spec.like_table)?;
    let if_not_exists = if spec.if_not_exists {
        "IF NOT EXISTS "
    } else {
        ""
    };
    let sql = match dialect {
        Dialect::Postgres => {
            format!("CREATE TABLE {if_not_exists}{table} (LIKE {like} INCLUDING ALL);")
        }
        Dialect::Mysql => format!("CREATE TABLE {if_not_exists}{table} LIKE {like};"),
        Dialect::Sqlite => {
            format!("CREATE TABLE {if_not_exists}{table} AS SELECT * FROM {like} WHERE 0;")
        }
    };
    Ok(sql)
}

pub fn compile_create_index(spec: &CreateIndexSpec, dialect: Dialect) -> Result<String, String> {
    let unique = if spec.unique { "UNIQUE " } else { "" };
    let name = dialect.quote_ident(&spec.name)?;
    let table = dialect.quote_ident(&spec.table)?;
    let cols: Result<Vec<String>, String> = spec.columns.iter().map(|c| dialect.quote_ident(c)).collect();
    Ok(format!("CREATE {}INDEX {} ON {} ({});", unique, name, table, cols?.join(", ")))
}

pub fn compile_drop_index(spec: &DropIndexSpec, dialect: Dialect) -> Result<String, String> {
    let name = dialect.quote_ident(&spec.name)?;
    let if_exists = if spec.if_exists { "IF EXISTS " } else { "" };
    Ok(format!("DROP INDEX {}{};", if_exists, name))
}

/// `CREATE [OR REPLACE] [MATERIALIZED] VIEW name [(cols)] AS <select>`.
///
/// The view NAME (and any column-list names) go through `quote_ident`, so they
/// are validated and quoted like every other identifier. The SELECT body is
/// raw, developer-authored migration SQL — the same trust level as `raw()` — so
/// it is embedded verbatim rather than parameterized.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateViewSpec {
    pub name: String,
    /// Raw SELECT body (without a trailing `;`).
    pub select: String,
    #[serde(default)]
    pub or_replace: bool,
    #[serde(default)]
    pub materialized: bool,
    #[serde(default)]
    pub columns: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DropViewSpec {
    pub name: String,
    #[serde(default)]
    pub if_exists: bool,
    #[serde(default)]
    pub materialized: bool,
}

pub fn compile_create_view(spec: &CreateViewSpec, dialect: Dialect) -> Result<String, String> {
    // Trim a trailing terminator so the caller can pass a bare SELECT or a
    // `SELECT ...;` without producing `... ;;`.
    let select = spec.select.trim().trim_end_matches(';').trim_end();
    if select.is_empty() {
        return Err("E_EMPTY_VIEW_SELECT: createView requires a non-empty SELECT body".into());
    }
    // Materialized views exist only on Postgres. SQLite/MySQL have none.
    if spec.materialized && dialect != Dialect::Postgres {
        return Err("E_UNSUPPORTED: materialized views are Postgres-only".into());
    }
    // SQLite has no CREATE OR REPLACE VIEW (drop then create instead).
    if spec.or_replace && dialect == Dialect::Sqlite {
        return Err("E_UNSUPPORTED: SQLite does not support CREATE OR REPLACE VIEW".into());
    }
    // Postgres rejects OR REPLACE on a MATERIALIZED view.
    if spec.or_replace && spec.materialized {
        return Err(
            "E_UNSUPPORTED: CREATE OR REPLACE is not valid for materialized views".into(),
        );
    }
    let name = dialect.quote_ident(&spec.name)?;
    let or_replace = if spec.or_replace { "OR REPLACE " } else { "" };
    let materialized = if spec.materialized { "MATERIALIZED " } else { "" };
    let columns = match &spec.columns {
        Some(cols) if !cols.is_empty() => {
            let quoted: Result<Vec<String>, String> =
                cols.iter().map(|c| dialect.quote_ident(c)).collect();
            format!(" ({})", quoted?.join(", "))
        }
        _ => String::new(),
    };
    Ok(format!(
        "CREATE {}{}VIEW {}{} AS {};",
        or_replace, materialized, name, columns, select
    ))
}

pub fn compile_drop_view(spec: &DropViewSpec, dialect: Dialect) -> Result<String, String> {
    if spec.materialized && dialect != Dialect::Postgres {
        return Err("E_UNSUPPORTED: materialized views are Postgres-only".into());
    }
    let name = dialect.quote_ident(&spec.name)?;
    let if_exists = if spec.if_exists { "IF EXISTS " } else { "" };
    let materialized = if spec.materialized { "MATERIALIZED " } else { "" };
    Ok(format!("DROP {}VIEW {}{};", materialized, if_exists, name))
}

/// One column-level ALTER TABLE operation. Tagged union — TypeScript sends
/// `{ op: "addColumn", column: {...} }` etc.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "camelCase")]
pub enum AlterOp {
    AddColumn { column: ColumnDef },
    DropColumn { name: String },
    RenameColumn { from: String, to: String },
    /// Change a column's type / nullability. Postgres + MySQL only — SQLite
    /// cannot alter a column in place (the table must be recreated).
    ///
    /// `set_nullable` is tri-state on purpose: `None` leaves the existing
    /// nullability untouched, so a bare type change never silently adds or
    /// drops a NOT NULL constraint just because `ColumnDef.nullable` defaults
    /// to `false`. Only an explicit `.nullable()` / `.notNullable()` before
    /// `.alter()` sets it.
    // `rename_all` on the enum renames the VARIANTS, not their fields — a
    // multi-word field needs its own attribute or it silently stays snake_case
    // and `serde(default)` swallows the camelCase key TypeScript actually sends.
    #[serde(rename_all = "camelCase")]
    AlterColumn {
        column: ColumnDef,
        #[serde(default)]
        set_nullable: Option<bool>,
    },
    /// Toggle NOT NULL without restating the column type (Lucid/Knex
    /// `setNullable` / `dropNullable`). Postgres-only: MySQL's `MODIFY COLUMN`
    /// requires the full type, and SQLite cannot alter a column in place.
    SetNullable { name: String, nullable: bool },
    /// Add a table-level constraint. Rejected on SQLite, which cannot add a
    /// constraint after the fact — Knex refuses this too.
    AddConstraint { constraint: TableConstraint },
    /// Drop a named constraint (`dropChecks`, and the named form of the
    /// `dropUnique`/`dropForeign` family).
    DropConstraint { name: String },
    /// Drop the primary key (Lucid/Knex `dropPrimary`). MySQL spells it
    /// `DROP PRIMARY KEY`; Postgres drops the named constraint.
    DropPrimary { #[serde(default)] name: Option<String> },
    /// Drop a unique constraint (Lucid/Knex `dropUnique`). On MySQL a unique
    /// constraint is an index, so it drops by index name.
    DropUnique { name: String },
    /// Drop a foreign key (Lucid/Knex `dropForeign`). MySQL spells it
    /// `DROP FOREIGN KEY`; Postgres drops the constraint.
    DropForeign { name: String },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AlterTableSpec {
    pub table: String,
    pub operations: Vec<AlterOp>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RenameTableSpec {
    pub table: String,
    pub to: String,
}

/// Compile ALTER TABLE → SQL statements, in call order. One operation can emit
/// more than one statement (Postgres splits a type change and a nullability
/// change into two `ALTER COLUMN` clauses), so results are flattened.
pub fn compile_alter_table(spec: &AlterTableSpec, dialect: Dialect) -> Result<Vec<String>, String> {
    if spec.operations.is_empty() {
        return Err("ALTER TABLE requires at least one operation".into());
    }
    let table = dialect.quote_ident(&spec.table)?;
    let per_op: Result<Vec<Vec<String>>, String> = spec.operations.iter().map(|op| match op {
        AlterOp::AddColumn { column } => {
            let mut stmts = vec![format!(
                "ALTER TABLE {} ADD COLUMN {}{};",
                table,
                render_column_def(column, dialect)?,
                render_position(column.position.as_ref(), dialect)?
            )];
            stmts.extend(column_comment_stmts(&spec.table, std::slice::from_ref(column), dialect)?);
            Ok(stmts)
        }
        AlterOp::DropColumn { name } => Ok(vec![format!(
            "ALTER TABLE {} DROP COLUMN {};",
            table,
            dialect.quote_ident(name)?
        )]),
        AlterOp::RenameColumn { from, to } => Ok(vec![format!(
            "ALTER TABLE {} RENAME COLUMN {} TO {};",
            table,
            dialect.quote_ident(from)?,
            dialect.quote_ident(to)?
        )]),
        AlterOp::AlterColumn { column, set_nullable } => match dialect {
            // Postgres: the physical type and the NOT NULL constraint are two
            // separate clauses. Nullability moves only when `set_nullable` says
            // so — see the `AlterOp::AlterColumn` docs for why it's tri-state.
            Dialect::Postgres => {
                let name = dialect.quote_ident(&column.name)?;
                let mut stmts = vec![format!(
                    "ALTER TABLE {} ALTER COLUMN {} TYPE {};",
                    table,
                    name,
                    dialect.map_column_type(&column.type_spec)?
                )];
                if let Some(nullable) = set_nullable {
                    stmts.push(nullability_stmt(&table, &name, *nullable));
                }
                Ok(stmts)
            }
            // MySQL rewrites the full column definition, so nullability rides
            // along inside `render_column_def` via `ColumnDef.nullable`. An
            // explicit `set_nullable` overrides it; otherwise the rendered
            // default (NOT NULL) would be a silent constraint change.
            Dialect::Mysql => {
                let mut col = column.clone();
                if let Some(nullable) = set_nullable {
                    col.nullable = *nullable;
                }
                Ok(vec![format!(
                    "ALTER TABLE {} MODIFY COLUMN {};",
                    table,
                    render_column_def(&col, dialect)?
                )])
            }
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot ALTER COLUMN in place — recreate the table instead".into(),
            ),
        },
        AlterOp::AddConstraint { constraint } => match dialect {
            // Knex raises the same refusal: SQLite cannot add a constraint to
            // an existing table (the table has to be rebuilt).
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot add a constraint to an existing table — declare it in createTable()".into(),
            ),
            _ => Ok(vec![format!(
                "ALTER TABLE {} ADD {};",
                table,
                render_table_constraint(constraint, dialect)?
            )]),
        },
        AlterOp::DropConstraint { name } => match dialect {
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot drop a constraint — recreate the table instead".into(),
            ),
            _ => Ok(vec![format!(
                "ALTER TABLE {} DROP CONSTRAINT {};",
                table,
                dialect.quote_ident(name)?
            )]),
        },
        AlterOp::DropPrimary { name } => match dialect {
            Dialect::Mysql => Ok(vec![format!("ALTER TABLE {} DROP PRIMARY KEY;", table)]),
            Dialect::Postgres => {
                // Postgres drops the constraint by name; its default is `<table>_pkey`.
                let constraint = name.clone().unwrap_or_else(|| format!("{}_pkey", spec.table));
                Ok(vec![format!(
                    "ALTER TABLE {} DROP CONSTRAINT {};",
                    table,
                    dialect.quote_ident(&constraint)?
                )])
            }
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot drop a primary key — recreate the table instead".into(),
            ),
        },
        AlterOp::DropUnique { name } => match dialect {
            // On MySQL a unique constraint IS an index and drops as one.
            Dialect::Mysql => Ok(vec![format!(
                "ALTER TABLE {} DROP INDEX {};",
                table,
                dialect.quote_ident(name)?
            )]),
            Dialect::Postgres => Ok(vec![format!(
                "ALTER TABLE {} DROP CONSTRAINT {};",
                table,
                dialect.quote_ident(name)?
            )]),
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot drop a unique constraint — drop the index with schema.dropIndex() if you created one".into(),
            ),
        },
        AlterOp::DropForeign { name } => match dialect {
            Dialect::Mysql => Ok(vec![format!(
                "ALTER TABLE {} DROP FOREIGN KEY {};",
                table,
                dialect.quote_ident(name)?
            )]),
            Dialect::Postgres => Ok(vec![format!(
                "ALTER TABLE {} DROP CONSTRAINT {};",
                table,
                dialect.quote_ident(name)?
            )]),
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot drop a foreign key — recreate the table instead".into(),
            ),
        },
        AlterOp::SetNullable { name, nullable } => match dialect {
            Dialect::Postgres => Ok(vec![nullability_stmt(
                &table,
                &dialect.quote_ident(name)?,
                *nullable,
            )]),
            Dialect::Mysql => Err(format!(
                "E_UNSUPPORTED: MySQL cannot toggle NOT NULL without restating the column type — use `table.<type>('{}').{}().alter()` instead",
                name,
                if *nullable { "nullable" } else { "notNullable" }
            )),
            Dialect::Sqlite => Err(
                "E_UNSUPPORTED: SQLite cannot ALTER COLUMN in place — recreate the table instead".into(),
            ),
        },
    }).collect();
    Ok(per_op?.into_iter().flatten().collect())
}

/// MySQL `FIRST` / `AFTER col` placement clause for an added column. Postgres
/// and SQLite always append, so asking for a position there is an error rather
/// than a silently ignored instruction.
fn render_position(
    position: Option<&ColumnPosition>,
    dialect: Dialect,
) -> Result<String, String> {
    let Some(position) = position else { return Ok(String::new()) };
    if dialect != Dialect::Mysql {
        return Err(
            "E_UNSUPPORTED: first()/after() is MySQL-only — Postgres and SQLite always append a new column".into(),
        );
    }
    Ok(match position {
        ColumnPosition::First => " FIRST".to_string(),
        ColumnPosition::After { column } => format!(" AFTER {}", dialect.quote_ident(column)?),
    })
}

/// Postgres `SET`/`DROP NOT NULL` clause. Both identifiers must already be quoted.
fn nullability_stmt(table: &str, column: &str, nullable: bool) -> String {
    format!(
        "ALTER TABLE {} ALTER COLUMN {} {} NOT NULL;",
        table,
        column,
        if nullable { "DROP" } else { "SET" }
    )
}

/// Compile RENAME TABLE — `ALTER TABLE old RENAME TO new` (portable across all three dialects).
pub fn compile_rename_table(spec: &RenameTableSpec, dialect: Dialect) -> Result<String, String> {
    Ok(format!(
        "ALTER TABLE {} RENAME TO {};",
        dialect.quote_ident(&spec.table)?,
        dialect.quote_ident(&spec.to)?
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dialect::ColumnTypeKind;
    use serde_json::json;

    fn col(name: &str, kind: ColumnTypeKind) -> ColumnDef {
        ColumnDef {
            name: name.into(),
            type_spec: ColumnTypeSpec { kind, length: None, precision: None, scale: None, values: None, raw_type: None },
            nullable: true,
            primary: false,
            auto_increment: false,
            unique: false,
            unsigned: false,
            default: None,
            references: None,
            comment: None,
            collate: None,
            position: None,
        }
    }

    #[test]
    fn create_table_sqlite() {
        let spec = CreateTableSpec {
            table: "users".into(),
            columns: vec![
                ColumnDef { primary: true, nullable: false, ..col("id", ColumnTypeKind::Integer) },
                ColumnDef { nullable: false, ..col("name", ColumnTypeKind::String) },
            ],
            indexes: vec![],
            if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        let stmts = compile_create_table(&spec, Dialect::Sqlite).unwrap();
        assert_eq!(stmts.len(), 1);
        assert!(stmts[0].contains("CREATE TABLE \"users\""));
        assert!(stmts[0].contains("\"id\" INTEGER PRIMARY KEY NOT NULL"));
        assert!(stmts[0].contains("\"name\" TEXT NOT NULL"));
    }

    #[test]
    fn auto_increment_per_dialect() {
        let make = || CreateTableSpec {
            table: "ream_migrations".into(),
            columns: vec![
                ColumnDef { auto_increment: true, nullable: false, ..col("id", ColumnTypeKind::Integer) },
                ColumnDef { nullable: false, unique: true, ..col("name", ColumnTypeKind::String) },
            ],
            indexes: vec![],
            if_not_exists: true, constraints: vec![], options: TableOptions::default(),
        };
        let sqlite = compile_create_table(&make(), Dialect::Sqlite).unwrap();
        assert!(sqlite[0].contains("\"id\" INTEGER PRIMARY KEY AUTOINCREMENT"));
        let pg = compile_create_table(&make(), Dialect::Postgres).unwrap();
        assert!(pg[0].contains("\"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"));
        let my = compile_create_table(&make(), Dialect::Mysql).unwrap();
        assert!(my[0].contains("`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY"));
    }

    #[test]
    fn big_increments_widens_to_64bit() {
        let make = || CreateTableSpec {
            table: "events".into(),
            columns: vec![ColumnDef {
                auto_increment: true,
                nullable: false,
                ..col("id", ColumnTypeKind::BigInteger)
            }],
            indexes: vec![],
            if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        assert!(compile_create_table(&make(), Dialect::Postgres).unwrap()[0]
            .contains("BIGINT GENERATED BY DEFAULT AS IDENTITY"));
        assert!(compile_create_table(&make(), Dialect::Mysql).unwrap()[0]
            .contains("BIGINT NOT NULL AUTO_INCREMENT"));
    }

    #[test]
    fn create_table_postgres_varchar() {
        let spec = CreateTableSpec {
            table: "users".into(),
            columns: vec![ColumnDef {
                nullable: false,
                type_spec: ColumnTypeSpec { kind: ColumnTypeKind::String, length: Some(100), precision: None, scale: None, values: None, raw_type: None },
                ..col("email", ColumnTypeKind::String)
            }],
            indexes: vec![],
            if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        let stmts = compile_create_table(&spec, Dialect::Postgres).unwrap();
        assert!(stmts[0].contains("\"email\" VARCHAR(100) NOT NULL"));
    }

    #[test]
    fn create_table_with_fk_and_index() {
        let spec = CreateTableSpec {
            table: "orders".into(),
            columns: vec![
                ColumnDef { primary: true, nullable: false, ..col("id", ColumnTypeKind::Integer) },
                ColumnDef {
                    nullable: false,
                    references: Some(ForeignKeyRef { table: "users".into(), column: "id".into(), on_delete: None, on_update: None }),
                    ..col("user_id", ColumnTypeKind::Integer)
                },
            ],
            indexes: vec![IndexDef { name: "idx_orders_user".into(), columns: vec!["user_id".into()], unique: false }],
            if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        let stmts = compile_create_table(&spec, Dialect::Sqlite).unwrap();
        assert_eq!(stmts.len(), 2);
        assert!(stmts[0].contains("REFERENCES \"users\"(\"id\")"));
        assert_eq!(stmts[1], "CREATE INDEX \"idx_orders_user\" ON \"orders\" (\"user_id\");");
    }

    #[test]
    fn fk_referential_actions() {
        let spec = CreateTableSpec {
            table: "orders".into(),
            columns: vec![ColumnDef {
                nullable: false,
                references: Some(ForeignKeyRef {
                    table: "users".into(),
                    column: "id".into(),
                    on_delete: Some("cascade".into()),
                    on_update: Some("set null".into()),
                }),
                ..col("user_id", ColumnTypeKind::Integer)
            }],
            indexes: vec![],
            if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        let stmts = compile_create_table(&spec, Dialect::Postgres).unwrap();
        assert!(stmts[0].contains("REFERENCES \"users\"(\"id\") ON DELETE CASCADE ON UPDATE SET NULL"), "sql: {}", stmts[0]);
    }

    #[test]
    fn fk_rejects_bad_action() {
        let spec = CreateTableSpec {
            table: "orders".into(),
            columns: vec![ColumnDef {
                references: Some(ForeignKeyRef {
                    table: "users".into(), column: "id".into(),
                    on_delete: Some("DROP TABLE".into()), on_update: None,
                }),
                ..col("user_id", ColumnTypeKind::Integer)
            }],
            indexes: vec![],
            if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        assert!(compile_create_table(&spec, Dialect::Sqlite).is_err());
    }

    #[test]
    fn alter_table_add_drop_rename() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![
                AlterOp::AddColumn { column: ColumnDef { nullable: false, ..col("age", ColumnTypeKind::Integer) } },
                AlterOp::DropColumn { name: "legacy".into() },
                AlterOp::RenameColumn { from: "name".into(), to: "full_name".into() },
            ],
        };
        let stmts = compile_alter_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(stmts.len(), 3);
        assert_eq!(stmts[0], "ALTER TABLE \"users\" ADD COLUMN \"age\" INTEGER NOT NULL;");
        assert_eq!(stmts[1], "ALTER TABLE \"users\" DROP COLUMN \"legacy\";");
        assert_eq!(stmts[2], "ALTER TABLE \"users\" RENAME COLUMN \"name\" TO \"full_name\";");
    }

    #[test]
    fn alter_column_per_dialect() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::AlterColumn {
                column: ColumnDef {
                    type_spec: ColumnTypeSpec { kind: ColumnTypeKind::String, length: Some(120), precision: None, scale: None, values: None, raw_type: None },
                    ..col("email", ColumnTypeKind::String)
                },
                set_nullable: None,
            }],
        };
        assert_eq!(
            compile_alter_table(&spec, Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"users\" ALTER COLUMN \"email\" TYPE VARCHAR(120);"
        );
        assert!(compile_alter_table(&spec, Dialect::Mysql).unwrap()[0]
            .starts_with("ALTER TABLE `users` MODIFY COLUMN `email` VARCHAR(120)"));
        assert!(compile_alter_table(&spec, Dialect::Sqlite).is_err());
    }

    /// A bare type change must not touch NOT NULL: `ColumnDef.nullable`
    /// defaults to false, so without the tri-state it would silently add one.
    #[test]
    fn alter_column_leaves_nullability_alone_by_default() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::AlterColumn {
                column: ColumnDef { nullable: false, ..col("email", ColumnTypeKind::Text) },
                set_nullable: None,
            }],
        };
        let pg = compile_alter_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(pg.len(), 1);
        assert!(!pg[0].contains("NOT NULL"));
    }

    #[test]
    fn alter_column_applies_explicit_nullability() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::AlterColumn {
                column: col("email", ColumnTypeKind::Text),
                set_nullable: Some(false),
            }],
        };
        let pg = compile_alter_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(pg.len(), 2);
        assert_eq!(pg[0], "ALTER TABLE \"users\" ALTER COLUMN \"email\" TYPE TEXT;");
        assert_eq!(pg[1], "ALTER TABLE \"users\" ALTER COLUMN \"email\" SET NOT NULL;");
        // MySQL folds nullability into the restated definition.
        let my = compile_alter_table(&spec, Dialect::Mysql).unwrap();
        assert_eq!(my.len(), 1);
        assert!(my[0].contains("NOT NULL"));
    }

    #[test]
    fn set_nullable_is_postgres_only() {
        let spec = |nullable| AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::SetNullable { name: "email".into(), nullable }],
        };
        assert_eq!(
            compile_alter_table(&spec(true), Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"users\" ALTER COLUMN \"email\" DROP NOT NULL;"
        );
        assert_eq!(
            compile_alter_table(&spec(false), Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"users\" ALTER COLUMN \"email\" SET NOT NULL;"
        );
        // MySQL needs the type restated; the error must say so.
        let err = compile_alter_table(&spec(true), Dialect::Mysql).unwrap_err();
        assert!(err.contains("E_UNSUPPORTED"), "{err}");
        assert!(err.contains(".alter()"), "{err}");
        assert!(compile_alter_table(&spec(true), Dialect::Sqlite).is_err());
    }

    #[test]
    fn alter_table_rejects_injected_identifiers() {
        let spec = AlterTableSpec {
            table: "users".into(),
            operations: vec![AlterOp::DropColumn { name: "x\"; DROP TABLE users; --".into() }],
        };
        assert!(compile_alter_table(&spec, Dialect::Postgres).is_err());
    }

    /// Wire-contract guard: TypeScript sends `setNullable` (camelCase). With
    /// only the enum-level `rename_all`, serde looks for `set_nullable`, finds
    /// nothing, and `serde(default)` quietly yields `None` — the nullability
    /// change vanishes with no error. Assert the camelCase key is honoured.
    #[test]
    fn alter_column_deserialises_camel_case_set_nullable() {
        let json = r#"{
            "table": "users",
            "operations": [
                { "op": "alterColumn", "setNullable": false,
                  "column": { "name": "email", "kind": "text", "nullable": true } }
            ]
        }"#;
        let spec: AlterTableSpec = serde_json::from_str(json).unwrap();
        let stmts = compile_alter_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(stmts.len(), 2, "setNullable was dropped on the wire: {stmts:?}");
        assert_eq!(stmts[1], "ALTER TABLE \"users\" ALTER COLUMN \"email\" SET NOT NULL;");
    }

    fn check(expr: CheckExpr) -> TableConstraint {
        TableConstraint::Check { name: None, expr }
    }

    fn spec_with(constraints: Vec<TableConstraint>) -> CreateTableSpec {
        CreateTableSpec {
            table: "t".into(),
            columns: vec![col("id", ColumnTypeKind::Integer)],
            indexes: vec![],
            if_not_exists: false,
            constraints,
            options: TableOptions::default(),
        }
    }

    /// The rendered CHECK body for `expr` on `dialect`, without the wrapper.
    fn check_sql(expr: CheckExpr, dialect: Dialect) -> String {
        render_check_expr(&expr, dialect).unwrap()
    }

    #[test]
    fn check_helpers_render_knex_predicates() {
        assert_eq!(
            check_sql(CheckExpr::Positive { column: "qty".into() }, Dialect::Postgres),
            "\"qty\" > 0"
        );
        assert_eq!(
            check_sql(CheckExpr::Negative { column: "qty".into() }, Dialect::Postgres),
            "\"qty\" < 0"
        );
        assert_eq!(
            check_sql(
                CheckExpr::In { column: "role".into(), values: vec![json!("a"), json!("b")] },
                Dialect::Postgres
            ),
            "\"role\" IN ('a', 'b')"
        );
        assert_eq!(
            check_sql(
                CheckExpr::NotIn { column: "role".into(), values: vec![json!("x")] },
                Dialect::Postgres
            ),
            "\"role\" NOT IN ('x')"
        );
        assert_eq!(
            check_sql(
                CheckExpr::Length { column: "code".into(), operator: "<=".into(), length: 8 },
                Dialect::Postgres
            ),
            "LENGTH(\"code\") <= 8"
        );
    }

    /// Knex ORs multiple intervals together.
    #[test]
    fn check_between_ors_intervals() {
        assert_eq!(
            check_sql(
                CheckExpr::Between { column: "n".into(), ranges: vec![vec![json!(1), json!(10)]] },
                Dialect::Postgres
            ),
            "\"n\" BETWEEN 1 AND 10"
        );
        assert_eq!(
            check_sql(
                CheckExpr::Between {
                    column: "n".into(),
                    ranges: vec![vec![json!(1), json!(10)], vec![json!(20), json!(30)]],
                },
                Dialect::Postgres
            ),
            "\"n\" BETWEEN 1 AND 10 OR \"n\" BETWEEN 20 AND 30"
        );
    }

    #[test]
    fn check_between_rejects_a_malformed_interval() {
        let expr = CheckExpr::Between { column: "n".into(), ranges: vec![vec![json!(1)]] };
        assert!(render_check_expr(&expr, Dialect::Postgres).is_err());
    }

    /// Postgres spells regex match `~`; SQLite and MySQL use `REGEXP`.
    #[test]
    fn check_regex_is_dialect_specific() {
        let expr = || CheckExpr::Regex { column: "sku".into(), pattern: "^[A-Z]+$".into() };
        assert_eq!(check_sql(expr(), Dialect::Postgres), "\"sku\" ~ '^[A-Z]+$'");
        assert_eq!(check_sql(expr(), Dialect::Mysql), "`sku` REGEXP '^[A-Z]+$'");
        assert_eq!(check_sql(expr(), Dialect::Sqlite), "\"sku\" REGEXP '^[A-Z]+$'");
    }

    /// DDL cannot bind parameters, so every CHECK value is interpolated — the
    /// literal quoting is the only thing between a migration and an injection.
    #[test]
    fn check_values_are_quoted_not_interpolated_raw() {
        let sql = check_sql(
            CheckExpr::In {
                column: "role".into(),
                values: vec![json!("a') OR 1=1 --")],
            },
            Dialect::Postgres,
        );
        assert_eq!(sql, "\"role\" IN ('a'') OR 1=1 --')");

        let regex = check_sql(
            CheckExpr::Regex { column: "x".into(), pattern: "a') OR 1=1 --".into() },
            Dialect::Postgres,
        );
        assert!(regex.contains("''"), "regex literal was not escaped: {regex}");
    }

    #[test]
    fn check_rejects_non_scalar_values_and_bad_operators() {
        assert!(render_check_expr(
            &CheckExpr::In { column: "x".into(), values: vec![json!({"a": 1})] },
            Dialect::Postgres
        )
        .is_err());
        assert!(render_check_expr(
            &CheckExpr::In { column: "x".into(), values: vec![] },
            Dialect::Postgres
        )
        .is_err());
        assert!(render_check_expr(
            &CheckExpr::Length { column: "x".into(), operator: "; DROP TABLE t --".into(), length: 1 },
            Dialect::Postgres
        )
        .is_err());
    }

    #[test]
    fn booleans_render_per_dialect() {
        assert_eq!(render_scalar_literal(&json!(true), Dialect::Postgres).unwrap(), "TRUE");
        assert_eq!(render_scalar_literal(&json!(true), Dialect::Sqlite).unwrap(), "1");
        assert_eq!(render_scalar_literal(&json!(false), Dialect::Mysql).unwrap(), "0");
    }

    #[test]
    fn composite_constraints_render_inline() {
        let spec = spec_with(vec![
            TableConstraint::Primary { name: None, columns: vec!["a".into(), "b".into()] },
            TableConstraint::Unique {
                name: Some("t_a_b_unique".into()),
                columns: vec!["a".into(), "b".into()],
            },
            TableConstraint::Foreign {
                name: None,
                columns: vec!["a".into()],
                references: ForeignKeyRefMulti {
                    table: "other".into(),
                    columns: vec!["id".into()],
                    on_delete: Some("cascade".into()),
                    on_update: None,
                },
            },
        ]);
        let sql = &compile_create_table(&spec, Dialect::Postgres).unwrap()[0];
        assert!(sql.contains("PRIMARY KEY (\"a\", \"b\")"), "{sql}");
        assert!(sql.contains("CONSTRAINT \"t_a_b_unique\" UNIQUE (\"a\", \"b\")"), "{sql}");
        assert!(
            sql.contains("FOREIGN KEY (\"a\") REFERENCES \"other\" (\"id\") ON DELETE CASCADE"),
            "{sql}"
        );
    }

    #[test]
    fn check_constraint_renders_inline_in_create_table() {
        let spec = spec_with(vec![check(CheckExpr::Positive { column: "id".into() })]);
        let sql = &compile_create_table(&spec, Dialect::Sqlite).unwrap()[0];
        assert!(sql.contains("CHECK (\"id\" > 0)"), "{sql}");
    }

    #[test]
    fn constraints_reject_injected_identifiers_and_empty_columns() {
        let evil = spec_with(vec![TableConstraint::Primary {
            name: None,
            columns: vec!["a\"; DROP TABLE t; --".into()],
        }]);
        assert!(compile_create_table(&evil, Dialect::Postgres).is_err());

        let empty = spec_with(vec![TableConstraint::Unique { name: None, columns: vec![] }]);
        assert!(compile_create_table(&empty, Dialect::Postgres).is_err());
    }

    #[test]
    fn column_comments_are_inline_on_mysql_and_separate_on_postgres() {
        let mut spec = spec_with(vec![]);
        spec.columns[0].comment = Some("the id".into());

        let my = compile_create_table(&spec, Dialect::Mysql).unwrap();
        assert_eq!(my.len(), 1);
        assert!(my[0].contains("COMMENT 'the id'"), "{:?}", my[0]);

        let pg = compile_create_table(&spec, Dialect::Postgres).unwrap();
        assert_eq!(pg.len(), 2);
        assert_eq!(pg[1], "COMMENT ON COLUMN \"t\".\"id\" IS 'the id';");

        // SQLite has no column comments — it must not leak into the DDL.
        let lite = compile_create_table(&spec, Dialect::Sqlite).unwrap();
        assert_eq!(lite.len(), 1);
        assert!(!lite[0].contains("COMMENT"), "{:?}", lite[0]);
    }

    #[test]
    fn table_options_are_mysql_only_except_the_postgres_comment() {
        let mut spec = spec_with(vec![]);
        spec.options = TableOptions {
            engine: Some("InnoDB".into()),
            charset: Some("utf8mb4".into()),
            collate: Some("utf8mb4_unicode_ci".into()),
            comment: Some("people".into()),
        };

        let my = compile_create_table(&spec, Dialect::Mysql).unwrap();
        assert!(my[0].contains("ENGINE = `InnoDB`"), "{:?}", my[0]);
        assert!(my[0].contains("DEFAULT CHARSET = `utf8mb4`"), "{:?}", my[0]);
        assert!(my[0].contains("COMMENT = 'people'"), "{:?}", my[0]);

        // Postgres takes none of the storage options, but does take the comment.
        let pg = compile_create_table(&spec, Dialect::Postgres).unwrap();
        assert!(!pg[0].contains("ENGINE"), "{:?}", pg[0]);
        assert!(pg.iter().any(|s| s == "COMMENT ON TABLE \"t\" IS 'people';"), "{pg:?}");

        let lite = compile_create_table(&spec, Dialect::Sqlite).unwrap();
        assert_eq!(lite.len(), 1);
        assert!(!lite[0].contains("ENGINE"), "{:?}", lite[0]);
    }

    #[test]
    fn drop_constraint_ops_are_dialect_specific() {
        let alter = |op| AlterTableSpec { table: "t".into(), operations: vec![op] };

        assert_eq!(
            compile_alter_table(&alter(AlterOp::DropPrimary { name: None }), Dialect::Mysql).unwrap()[0],
            "ALTER TABLE `t` DROP PRIMARY KEY;"
        );
        // Postgres drops the named constraint; its default name is <table>_pkey.
        assert_eq!(
            compile_alter_table(&alter(AlterOp::DropPrimary { name: None }), Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"t\" DROP CONSTRAINT \"t_pkey\";"
        );
        // On MySQL a unique constraint is an index.
        assert_eq!(
            compile_alter_table(&alter(AlterOp::DropUnique { name: "u".into() }), Dialect::Mysql).unwrap()[0],
            "ALTER TABLE `t` DROP INDEX `u`;"
        );
        assert_eq!(
            compile_alter_table(&alter(AlterOp::DropUnique { name: "u".into() }), Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"t\" DROP CONSTRAINT \"u\";"
        );
        assert_eq!(
            compile_alter_table(&alter(AlterOp::DropForeign { name: "f".into() }), Dialect::Mysql).unwrap()[0],
            "ALTER TABLE `t` DROP FOREIGN KEY `f`;"
        );
        assert_eq!(
            compile_alter_table(&alter(AlterOp::DropConstraint { name: "c".into() }), Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"t\" DROP CONSTRAINT \"c\";"
        );

        // SQLite can drop none of them.
        for op in [
            AlterOp::DropPrimary { name: None },
            AlterOp::DropUnique { name: "u".into() },
            AlterOp::DropForeign { name: "f".into() },
            AlterOp::DropConstraint { name: "c".into() },
        ] {
            assert!(compile_alter_table(&alter(op), Dialect::Sqlite).is_err());
        }
    }

    /// Knex refuses this on SQLite too — the table must be rebuilt.
    #[test]
    fn adding_a_constraint_is_rejected_on_sqlite() {
        let spec = AlterTableSpec {
            table: "t".into(),
            operations: vec![AlterOp::AddConstraint {
                constraint: check(CheckExpr::Positive { column: "id".into() }),
            }],
        };
        assert!(compile_alter_table(&spec, Dialect::Sqlite).is_err());
        assert_eq!(
            compile_alter_table(&spec, Dialect::Postgres).unwrap()[0],
            "ALTER TABLE \"t\" ADD CHECK (\"id\" > 0);"
        );
    }

    #[test]
    fn column_position_is_mysql_only() {
        let with_pos = |position| AlterTableSpec {
            table: "t".into(),
            operations: vec![AlterOp::AddColumn {
                column: ColumnDef { position: Some(position), ..col("x", ColumnTypeKind::Text) },
            }],
        };
        assert!(compile_alter_table(&with_pos(ColumnPosition::First), Dialect::Mysql).unwrap()[0]
            .ends_with(" FIRST;"));
        assert!(compile_alter_table(
            &with_pos(ColumnPosition::After { column: "id".into() }),
            Dialect::Mysql
        )
        .unwrap()[0]
            .ends_with(" AFTER `id`;"));
        // pg/sqlite always append — asking for a position must not be ignored silently.
        assert!(compile_alter_table(&with_pos(ColumnPosition::First), Dialect::Postgres).is_err());
        assert!(compile_alter_table(&with_pos(ColumnPosition::First), Dialect::Sqlite).is_err());
    }

    #[test]
    fn alter_table_rejects_empty_operations() {
        let spec = AlterTableSpec { table: "users".into(), operations: vec![] };
        assert!(compile_alter_table(&spec, Dialect::Postgres).is_err());
    }

    #[test]
    fn rename_table_portable() {
        let spec = RenameTableSpec { table: "old".into(), to: "new".into() };
        assert_eq!(compile_rename_table(&spec, Dialect::Sqlite).unwrap(), "ALTER TABLE \"old\" RENAME TO \"new\";");
        assert_eq!(compile_rename_table(&spec, Dialect::Mysql).unwrap(), "ALTER TABLE `old` RENAME TO `new`;");
    }

    #[test]
    fn drop_table() {
        let spec = DropTableSpec { table: "old".into(), if_exists: true, cascade: false };
        assert_eq!(compile_drop_table(&spec, Dialect::Sqlite).unwrap(), "DROP TABLE IF EXISTS \"old\";");
    }

    #[test]
    fn drop_table_cascade_postgres_only() {
        // CASCADE renders on Postgres…
        let pg = DropTableSpec { table: "old".into(), if_exists: true, cascade: true };
        assert_eq!(
            compile_drop_table(&pg, Dialect::Postgres).unwrap(),
            "DROP TABLE IF EXISTS \"old\" CASCADE;"
        );
        // …but is suppressed on SQLite (keyword unsupported) and MySQL (no-op).
        let sqlite = DropTableSpec { table: "old".into(), if_exists: false, cascade: true };
        assert_eq!(compile_drop_table(&sqlite, Dialect::Sqlite).unwrap(), "DROP TABLE \"old\";");
        let mysql = DropTableSpec { table: "old".into(), if_exists: false, cascade: true };
        assert_eq!(compile_drop_table(&mysql, Dialect::Mysql).unwrap(), "DROP TABLE `old`;");
    }

    #[test]
    fn enum_mysql_native_pg_sqlite_check() {
        let mut c = col("status", ColumnTypeKind::Enum);
        c.type_spec.values = Some(vec!["active".into(), "inactive".into()]);
        c.nullable = false;
        let spec = CreateTableSpec {
            table: "t".into(), columns: vec![c], indexes: vec![], if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        // MySQL renders a native ENUM.
        assert!(compile_create_table(&spec, Dialect::Mysql).unwrap()[0]
            .contains("ENUM('active', 'inactive')"));
        // Postgres/SQLite render TEXT + a CHECK pinning the value set.
        let pg = compile_create_table(&spec, Dialect::Postgres).unwrap()[0].clone();
        assert!(pg.contains("\"status\" TEXT"), "sql: {}", pg);
        assert!(
            pg.contains("CHECK (\"status\" IN ('active', 'inactive'))"),
            "sql: {}", pg
        );
    }

    #[test]
    fn enum_escapes_quotes_and_rejects_empty() {
        // A single quote in a value is doubled, not left to break out of the literal.
        let mut c = col("s", ColumnTypeKind::Enum);
        c.type_spec.values = Some(vec!["O'Brien".into()]);
        let spec = CreateTableSpec {
            table: "t".into(), columns: vec![c], indexes: vec![], if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        assert!(compile_create_table(&spec, Dialect::Sqlite).unwrap()[0].contains("'O''Brien'"));
        // An empty value set is rejected rather than emitting `ENUM()` / `IN ()`.
        let mut e = col("s", ColumnTypeKind::Enum);
        e.type_spec.values = Some(vec![]);
        let espec = CreateTableSpec {
            table: "t".into(), columns: vec![e], indexes: vec![], if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        assert!(compile_create_table(&espec, Dialect::Sqlite).is_err());
    }

    #[test]
    fn unsigned_is_mysql_only() {
        let mut c = col("n", ColumnTypeKind::Integer);
        c.unsigned = true;
        let spec = CreateTableSpec {
            table: "t".into(), columns: vec![c], indexes: vec![], if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        assert!(compile_create_table(&spec, Dialect::Mysql).unwrap()[0].contains("INT UNSIGNED"));
        // pg/sqlite have no unsigned integers — the modifier is dropped.
        assert!(!compile_create_table(&spec, Dialect::Postgres).unwrap()[0].contains("UNSIGNED"));
        assert!(!compile_create_table(&spec, Dialect::Sqlite).unwrap()[0].contains("UNSIGNED"));
    }

    #[test]
    fn foreign_key_on_delete_on_update_render() {
        let mut c = col("author_id", ColumnTypeKind::Integer);
        c.references = Some(ForeignKeyRef {
            table: "users".into(),
            column: "id".into(),
            on_delete: Some("cascade".into()),
            on_update: Some("restrict".into()),
        });
        let spec = CreateTableSpec {
            table: "posts".into(), columns: vec![c], indexes: vec![], if_not_exists: false, constraints: vec![], options: TableOptions::default(),
        };
        let sql = compile_create_table(&spec, Dialect::Postgres).unwrap()[0].clone();
        assert!(
            sql.contains("REFERENCES \"users\"(\"id\") ON DELETE CASCADE ON UPDATE RESTRICT"),
            "sql: {}", sql
        );
    }

    #[test]
    fn create_index_unique() {
        let spec = CreateIndexSpec {
            table: "users".into(),
            name: "idx_users_email".into(),
            columns: vec!["email".into()],
            unique: true,
        };
        assert_eq!(
            compile_create_index(&spec, Dialect::Sqlite).unwrap(),
            "CREATE UNIQUE INDEX \"idx_users_email\" ON \"users\" (\"email\");"
        );
    }

    #[test]
    fn mysql_backticks_in_ddl() {
        let spec = DropTableSpec { table: "old".into(), if_exists: false, cascade: false };
        assert_eq!(compile_drop_table(&spec, Dialect::Mysql).unwrap(), "DROP TABLE `old`;");
    }

    #[test]
    fn rejects_injection_in_table_name() {
        let spec = DropTableSpec { table: "users; DROP TABLE admins--".into(), if_exists: false, cascade: false };
        assert!(compile_drop_table(&spec, Dialect::Sqlite).is_err());
    }

    fn view(name: &str, select: &str) -> CreateViewSpec {
        CreateViewSpec {
            name: name.into(),
            select: select.into(),
            or_replace: false,
            materialized: false,
            columns: None,
        }
    }

    #[test]
    fn create_view_basic() {
        let spec = view("active_users", "SELECT * FROM users WHERE active = 1");
        assert_eq!(
            compile_create_view(&spec, Dialect::Sqlite).unwrap(),
            "CREATE VIEW \"active_users\" AS SELECT * FROM users WHERE active = 1;"
        );
    }

    #[test]
    fn create_view_trims_trailing_semicolon() {
        let spec = view("v", "SELECT 1;");
        assert_eq!(
            compile_create_view(&spec, Dialect::Postgres).unwrap(),
            "CREATE VIEW \"v\" AS SELECT 1;"
        );
    }

    #[test]
    fn create_view_with_columns_and_or_replace() {
        let mut spec = view("v", "SELECT id, name FROM t");
        spec.columns = Some(vec!["a".into(), "b".into()]);
        spec.or_replace = true;
        assert_eq!(
            compile_create_view(&spec, Dialect::Postgres).unwrap(),
            "CREATE OR REPLACE VIEW \"v\" (\"a\", \"b\") AS SELECT id, name FROM t;"
        );
    }

    #[test]
    fn create_view_or_replace_rejected_on_sqlite() {
        let mut spec = view("v", "SELECT 1");
        spec.or_replace = true;
        assert!(compile_create_view(&spec, Dialect::Sqlite).is_err());
    }

    #[test]
    fn materialized_view_postgres_only() {
        let mut spec = view("mv", "SELECT 1");
        spec.materialized = true;
        assert_eq!(
            compile_create_view(&spec, Dialect::Postgres).unwrap(),
            "CREATE MATERIALIZED VIEW \"mv\" AS SELECT 1;"
        );
        assert!(compile_create_view(&spec, Dialect::Sqlite).is_err());
        assert!(compile_create_view(&spec, Dialect::Mysql).is_err());
    }

    #[test]
    fn create_view_rejects_empty_select_and_bad_name() {
        assert!(compile_create_view(&view("v", "   "), Dialect::Sqlite).is_err());
        assert!(
            compile_create_view(&view("v; DROP TABLE t--", "SELECT 1"), Dialect::Sqlite).is_err()
        );
    }

    #[test]
    fn drop_view_if_exists_and_materialized() {
        let spec = DropViewSpec { name: "v".into(), if_exists: true, materialized: false };
        assert_eq!(
            compile_drop_view(&spec, Dialect::Mysql).unwrap(),
            "DROP VIEW IF EXISTS `v`;"
        );
        let mv = DropViewSpec { name: "mv".into(), if_exists: false, materialized: true };
        assert_eq!(
            compile_drop_view(&mv, Dialect::Postgres).unwrap(),
            "DROP MATERIALIZED VIEW \"mv\";"
        );
        assert!(compile_drop_view(&mv, Dialect::Sqlite).is_err());
    }
}
