//! SQL dialect: identifier quoting + column type mapping.
//!
//! Drives all dialect differences in one place so the rest of the compiler
//! is dialect-agnostic.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum Dialect {
    #[default]
    Sqlite,
    Postgres,
    Mysql,
}

impl Dialect {
    pub fn from_name(name: &str) -> Result<Self, String> {
        match name.to_lowercase().as_str() {
            "sqlite" => Ok(Dialect::Sqlite),
            "postgres" | "postgresql" => Ok(Dialect::Postgres),
            "mysql" | "mariadb" => Ok(Dialect::Mysql),
            _ => Err(format!("unknown dialect: {}", name)),
        }
    }

    /// Quote character pair for identifiers: (`"`, `"`) for sqlite/postgres, (`` ` ``, `` ` ``) for mysql.
    pub fn quote_char(&self) -> char {
        match self {
            Dialect::Sqlite | Dialect::Postgres => '"',
            Dialect::Mysql => '`',
        }
    }

    /// Validate and quote an identifier. Supports schema-qualified names ("schema.table").
    pub fn quote_ident(&self, name: &str) -> Result<String, String> {
        if name == "*" {
            return Ok(name.to_string());
        }
        let q = self.quote_char();
        // Up to three dot-qualified segments: schema.table.column (matches the
        // select/where identifier quoter this backs).
        let parts: Vec<&str> = name.splitn(4, '.').collect();
        if parts.len() > 3 {
            return Err(format!("too many dot segments in identifier: '{}'", name));
        }
        for part in &parts {
            if part.is_empty() {
                return Err(format!("empty segment in identifier: '{}'", name));
            }
            if part.contains('\0') || part.contains(q) {
                return Err(format!(
                    "E_UNSAFE_IDENTIFIER: identifier contains an illegal character (quote or NUL): '{}'",
                    name
                ));
            }
            if !part.chars().all(|c| c.is_alphanumeric() || c == '_') {
                return Err(format!(
                    "E_UNSAFE_IDENTIFIER: invalid identifier '{}' — only letters, digits, and underscores are allowed",
                    name
                ));
            }
        }
        Ok(parts.iter().map(|p| format!("{}{}{}", q, p, q)).collect::<Vec<_>>().join("."))
    }

    /// Parameter placeholder for a given index: `$N` for Postgres, `?` for sqlite/mysql.
    pub fn placeholder(&self, index: u32) -> String {
        match self {
            Dialect::Postgres => format!("${}", index),
            Dialect::Sqlite | Dialect::Mysql => "?".into(),
        }
    }

    /// Render DEFAULT <expr>. SQLite wraps in parentheses for function calls.
    pub fn wrap_default(&self, value: &str) -> String {
        match self {
            Dialect::Sqlite => format!("DEFAULT ({})", value),
            _ => format!("DEFAULT {}", value),
        }
    }

    /// Render a dialect-appropriate auto-increment / identity PRIMARY KEY column
    /// (Lucid `increments()` / `bigIncrements()`). `BigInteger` widens to 64-bit
    /// where the dialect distinguishes; SQLite's `INTEGER PRIMARY KEY` rowid is
    /// always 64-bit so the keyword form is identical.
    pub fn auto_increment_column(&self, kind: ColumnTypeKind) -> String {
        let big = matches!(kind, ColumnTypeKind::BigInteger);
        match self {
            Dialect::Sqlite => "INTEGER PRIMARY KEY AUTOINCREMENT".into(),
            Dialect::Postgres => format!(
                "{} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                if big { "BIGINT" } else { "INTEGER" }
            ),
            Dialect::Mysql => format!(
                "{} NOT NULL AUTO_INCREMENT PRIMARY KEY",
                if big { "BIGINT" } else { "INT" }
            ),
        }
    }

    /// Postgres cast suffix for a bound parameter targeting a typed column.
    /// Returns `Some("timestamp")` etc. ONLY for Postgres: sqlx binds JS strings
    /// as `text`, and Postgres won't implicitly coerce `text` to
    /// timestamp/date/uuid/jsonb. SQLite and MySQL coerce fine, so they get
    /// `None` (plain placeholder). The logical type is lower-cased by the caller.
    pub fn cast_for(&self, logical_type: &str) -> Option<&'static str> {
        if !matches!(self, Dialect::Postgres) {
            return None;
        }
        match logical_type {
            "timestamp" | "datetime" => Some("timestamp"),
            // `timestamptz` is a distinct Postgres type — without its own arm the
            // TS whitelist (which accepts it) and this matcher diverge: the column
            // gets no cast and the text bind fails with "column is of type timestamp
            // with time zone but expression is of type text".
            "timestamptz" => Some("timestamptz"),
            "date" => Some("date"),
            "time" => Some("time"),
            "uuid" => Some("uuid"),
            "json" | "jsonb" => Some("jsonb"),
            // `numeric`/`decimal` columns: sqlx binds a JS string as `text`, and
            // Postgres has no implicit text→numeric assignment cast, so a money
            // column tagged with the decimal adapter (`@c9up/atom/atlas`) fails
            // with "column is of type numeric but expression is of type text".
            // An explicit `$N::numeric` lets the lossless string form bind without
            // ever going through a float.
            "numeric" | "decimal" => Some("numeric"),
            // Nullable integer columns: a JS number binds as a real int, but a JS
            // `null` binds as `text`, and Postgres won't coerce text→int on
            // assignment, so `SET col = NULL` on a nullable int column fails with
            // "column is of type integer but expression is of type text". Opt-in —
            // only columns explicitly tagged `@Column({ type: 'integer' })` reach
            // here, so untyped int columns keep their plain-number bind untouched.
            "integer" | "int" | "int4" => Some("int4"),
            "bigint" | "int8" => Some("int8"),
            "smallint" | "int2" => Some("int2"),
            // Nullable boolean / float columns hit the same text-bound-NULL issue.
            // `float`/`double`/`double precision` are Postgres aliases for float8.
            "boolean" | "bool" => Some("bool"),
            "real" | "float4" => Some("float4"),
            "double precision" | "double" | "float8" | "float" => Some("float8"),
            _ => None,
        }
    }

    /// Map a logical column type to the physical SQL type for this dialect.
    ///
    /// Fallible because `SpecificType` carries a caller-supplied string that is
    /// interpolated verbatim into DDL — returning `Result` here means a new
    /// call site cannot forget to validate it.
    pub fn map_column_type(&self, spec: &ColumnTypeSpec) -> Result<String, String> {
        use ColumnTypeKind::*;
        let length = spec.length.unwrap_or(255);
        let precision = spec.precision.unwrap_or(10);
        let scale = spec.scale.unwrap_or(2);

        // Types whose rendering depends on an optional argument, handled before
        // the flat match so the common arms stay readable.
        match spec.kind {
            SpecificType => {
                let raw = spec.raw_type.as_deref().ok_or(
                    "E_SPECIFIC_TYPE_EMPTY: specificType requires a type name",
                )?;
                return validate_specific_type(raw);
            }
            // `TIME(p)` / `TIMESTAMP(p)` / `TIMESTAMPTZ(p)` — fractional-second
            // precision (Lucid `{ precision }`). SQLite stores these as TEXT and
            // has no precision to apply.
            Time | Timestamp | Timestamptz if spec.precision.is_some() && *self != Dialect::Sqlite => {
                let base = match (self, spec.kind) {
                    (_, Time) => "TIME",
                    (Dialect::Postgres, Timestamptz) => "TIMESTAMPTZ",
                    (_, Timestamptz) => "TIMESTAMP",
                    (_, _) => "TIMESTAMP",
                };
                return Ok(format!("{}({})", base, precision));
            }
            // MySQL `VARBINARY(n)`; pg BYTEA and SQLite BLOB take no length.
            Binary if spec.length.is_some() && *self == Dialect::Mysql => {
                return Ok(format!("VARBINARY({})", length));
            }
            // `FLOAT(p, s)` / `DOUBLE(p, s)` — MySQL-only; pg/sqlite have fixed-width floats.
            Float | Double if spec.precision.is_some() && *self == Dialect::Mysql => {
                let base = if spec.kind == Float { "FLOAT" } else { "DOUBLE" };
                return Ok(format!("{}({}, {})", base, precision, scale));
            }
            _ => {}
        }

        Ok(match (self, spec.kind) {
            (Dialect::Postgres, Uuid) => "UUID".into(),
            (Dialect::Sqlite, Uuid) => "TEXT".into(),
            (Dialect::Mysql, Uuid) => "CHAR(36)".into(),

            (Dialect::Postgres, String) => format!("VARCHAR({})", length),
            (Dialect::Sqlite, String) => "TEXT".into(),
            (Dialect::Mysql, String) => format!("VARCHAR({})", length),

            (_, Text) => "TEXT".into(),

            (Dialect::Mysql, Integer) => "INT".into(),
            (_, Integer) => "INTEGER".into(),

            (Dialect::Mysql, TinyInt) => "TINYINT".into(),
            (Dialect::Postgres, TinyInt) => "SMALLINT".into(),
            (Dialect::Sqlite, TinyInt) => "INTEGER".into(),

            (Dialect::Sqlite, SmallInt) => "INTEGER".into(),
            (_, SmallInt) => "SMALLINT".into(),

            (Dialect::Sqlite, BigInteger) => "INTEGER".into(),
            (_, BigInteger) => "BIGINT".into(),

            (Dialect::Sqlite, Decimal) => "REAL".into(),
            (_, Decimal) => format!("DECIMAL({}, {})", precision, scale),

            (Dialect::Mysql, Float) => "FLOAT".into(),
            (_, Float) => "REAL".into(),

            (Dialect::Postgres, Double) => "DOUBLE PRECISION".into(),
            (Dialect::Sqlite, Double) => "REAL".into(),
            (Dialect::Mysql, Double) => "DOUBLE".into(),

            (Dialect::Postgres, Boolean) => "BOOLEAN".into(),
            (Dialect::Sqlite, Boolean) => "INTEGER".into(),
            (Dialect::Mysql, Boolean) => "TINYINT(1)".into(),

            (Dialect::Sqlite, Date) => "TEXT".into(),
            (_, Date) => "DATE".into(),

            (Dialect::Sqlite, Time) => "TEXT".into(),
            (_, Time) => "TIME".into(),

            (Dialect::Sqlite, Timestamp) => "TEXT".into(),
            (_, Timestamp) => "TIMESTAMP".into(),

            // `timestamptz` is a real Postgres type (UTC-normalised). Other
            // dialects have no equivalent, so it degrades to their plain
            // timestamp mapping (documented — true tz-safety is Postgres-only).
            (Dialect::Postgres, Timestamptz) => "TIMESTAMPTZ".into(),
            (Dialect::Sqlite, Timestamptz) => "TEXT".into(),
            (_, Timestamptz) => "TIMESTAMP".into(),

            (Dialect::Postgres, Json) => "JSONB".into(),
            (Dialect::Sqlite, Json) => "TEXT".into(),
            (Dialect::Mysql, Json) => "JSON".into(),

            (Dialect::Postgres, Binary) => "BYTEA".into(),
            (Dialect::Sqlite, Binary) => "BLOB".into(),
            (Dialect::Mysql, Binary) => "BLOB".into(),

            // Enum is rendered by `render_column_def` (it needs the value list and
            // the column name for the CHECK constraint / native ENUM literal). This
            // arm is only the fallback base type and keeps the match exhaustive.
            (_, Enum) => "TEXT".into(),

            (Dialect::Postgres, Jsonb) => "JSONB".into(),
            (Dialect::Sqlite, Jsonb) => "TEXT".into(),
            (Dialect::Mysql, Jsonb) => "JSON".into(),

            (Dialect::Mysql, MediumInt) => "MEDIUMINT".into(),
            (_, MediumInt) => "INTEGER".into(),

            (Dialect::Mysql, MediumText) => "MEDIUMTEXT".into(),
            (_, MediumText) => "TEXT".into(),

            (Dialect::Mysql, LongText) => "LONGTEXT".into(),
            (_, LongText) => "TEXT".into(),

            // Returned early above — it needs `raw_type` validation, and this
            // arm exists only to keep the match exhaustive.
            (_, SpecificType) => unreachable!("SpecificType is resolved before this match"),
        })
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ColumnTypeKind {
    Uuid,
    String,
    Text,
    Integer,
    /// 8-bit integer (Lucid `tinyint`). MySQL `TINYINT`; Postgres has none, so it
    /// widens to `SMALLINT`; SQLite `INTEGER`.
    TinyInt,
    /// 16-bit integer (Lucid `smallint`). `SMALLINT` on pg/mysql, `INTEGER` on SQLite.
    SmallInt,
    BigInteger,
    Decimal,
    /// Single-precision float (Lucid `float`). `REAL` on pg/sqlite, `FLOAT` on MySQL.
    Float,
    /// Double-precision float (Lucid `double`). `DOUBLE PRECISION` on pg, `REAL` on
    /// SQLite, `DOUBLE` on MySQL.
    Double,
    Boolean,
    Date,
    /// Time of day (Lucid `time`). `TIME` on pg/mysql, `TEXT` on SQLite.
    Time,
    Timestamp,
    /// `timestamp with time zone` — Postgres normalises every writer to UTC, so
    /// reads are unambiguous regardless of server TZ (unlike `Timestamp`). On
    /// dialects without a real tz type it degrades to the plain timestamp type.
    Timestamptz,
    Json,
    Binary,
    /// A fixed value set (Lucid `enum`). MySQL renders a native `ENUM(...)`;
    /// pg/sqlite render `TEXT` plus a column-level `CHECK (col IN (...))`. The
    /// allowed values travel in `ColumnTypeSpec::values`.
    Enum,
    /// Binary JSON (Lucid/Knex `jsonb`). `JSONB` on Postgres, `JSON` on MySQL,
    /// `TEXT` on SQLite.
    ///
    /// Deviation, named: atlas's `Json` ALSO maps to `JSONB` on Postgres (it
    /// predates this kind), where Lucid's `json()` maps to `json`. Keeping
    /// `Json` as-is avoids silently rewriting the physical type of existing
    /// columns and breaking `SchemaCheck` drift detection, so on Postgres the
    /// two kinds coincide.
    Jsonb,
    /// 24-bit integer (Lucid/Knex `mediumint`). MySQL `MEDIUMINT`; Postgres and
    /// SQLite have none, so both widen to `INTEGER`.
    MediumInt,
    /// MySQL `MEDIUMTEXT` (Lucid/Knex `text(name, 'mediumtext')`). `TEXT` elsewhere.
    MediumText,
    /// MySQL `LONGTEXT` (Lucid/Knex `text(name, 'longtext')`). `TEXT` elsewhere.
    LongText,
    /// A verbatim dialect type (Lucid/Knex `specificType`). The type string
    /// travels in `ColumnTypeSpec::raw_type` and is validated against a
    /// conservative grammar — it is interpolated into DDL, so it is an
    /// injection surface and cannot be passed through unchecked.
    SpecificType,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColumnTypeSpec {
    pub kind: ColumnTypeKind,
    #[serde(default)]
    pub length: Option<u32>,
    #[serde(default)]
    pub precision: Option<u32>,
    #[serde(default)]
    pub scale: Option<u32>,
    /// Allowed values for an `Enum` column (ignored for every other kind).
    #[serde(default)]
    pub values: Option<Vec<String>>,
    /// Verbatim type for a `SpecificType` column (ignored for every other
    /// kind). Validated by [`validate_specific_type`] before it reaches SQL.
    #[serde(default, rename = "rawType")]
    pub raw_type: Option<String>,
}

/// Validate a `specificType` string before it is interpolated into DDL.
///
/// Lucid/Knex pass this straight through; atlas cannot, because the value ends
/// up verbatim in a `CREATE TABLE`. The grammar is deliberately narrow —
/// letters, digits, spaces, `_`, and one optional parenthesised argument list
/// of digits/commas/spaces — which covers real type names (`inet`, `tsvector`,
/// `geometry(Point, 4326)`, `numeric(10, 2)`, `double precision`) while
/// rejecting anything that could close the statement or start a new one.
fn validate_specific_type(raw: &str) -> Result<String, String> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return Err("E_SPECIFIC_TYPE_EMPTY: specificType requires a type name".into());
    }
    if trimmed.len() > 128 {
        return Err("E_UNSAFE_SQL: specificType is too long to be a type name".into());
    }
    let mut depth = 0usize;
    for ch in trimmed.chars() {
        match ch {
            'a'..='z' | 'A'..='Z' | '0'..='9' | '_' | ' ' => {}
            ',' if depth == 1 => {}
            '(' if depth == 0 => depth = 1,
            ')' if depth == 1 => depth = 0,
            _ => {
                return Err(format!(
                    "E_UNSAFE_SQL: specificType {:?} contains an unsupported character {:?} — \
                     only letters, digits, spaces, underscores and one (…) argument list are allowed",
                    trimmed, ch
                ))
            }
        }
    }
    if depth != 0 {
        return Err(format!("E_UNSAFE_SQL: specificType {:?} has an unbalanced parenthesis", trimmed));
    }
    Ok(trimmed.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn kind_spec(kind: ColumnTypeKind) -> ColumnTypeSpec {
        ColumnTypeSpec { kind, length: None, precision: None, scale: None, values: None, raw_type: None }
    }

    #[test]
    fn jsonb_and_mediumint_map_per_dialect() {
        let jsonb = kind_spec(ColumnTypeKind::Jsonb);
        assert_eq!(Dialect::Postgres.map_column_type(&jsonb).unwrap(), "JSONB");
        assert_eq!(Dialect::Mysql.map_column_type(&jsonb).unwrap(), "JSON");
        assert_eq!(Dialect::Sqlite.map_column_type(&jsonb).unwrap(), "TEXT");

        let medium = kind_spec(ColumnTypeKind::MediumInt);
        assert_eq!(Dialect::Mysql.map_column_type(&medium).unwrap(), "MEDIUMINT");
        assert_eq!(Dialect::Postgres.map_column_type(&medium).unwrap(), "INTEGER");
        assert_eq!(Dialect::Sqlite.map_column_type(&medium).unwrap(), "INTEGER");
    }

    #[test]
    fn text_variants_widen_on_mysql_only() {
        for (kind, mysql) in [
            (ColumnTypeKind::MediumText, "MEDIUMTEXT"),
            (ColumnTypeKind::LongText, "LONGTEXT"),
        ] {
            let spec = kind_spec(kind);
            assert_eq!(Dialect::Mysql.map_column_type(&spec).unwrap(), mysql);
            assert_eq!(Dialect::Postgres.map_column_type(&spec).unwrap(), "TEXT");
            assert_eq!(Dialect::Sqlite.map_column_type(&spec).unwrap(), "TEXT");
        }
    }

    #[test]
    fn temporal_precision_is_applied_except_on_sqlite() {
        let spec = ColumnTypeSpec { precision: Some(3), ..kind_spec(ColumnTypeKind::Timestamp) };
        assert_eq!(Dialect::Postgres.map_column_type(&spec).unwrap(), "TIMESTAMP(3)");
        assert_eq!(Dialect::Mysql.map_column_type(&spec).unwrap(), "TIMESTAMP(3)");
        // SQLite stores timestamps as TEXT — there is no precision to carry.
        assert_eq!(Dialect::Sqlite.map_column_type(&spec).unwrap(), "TEXT");

        let tz = ColumnTypeSpec { precision: Some(6), ..kind_spec(ColumnTypeKind::Timestamptz) };
        assert_eq!(Dialect::Postgres.map_column_type(&tz).unwrap(), "TIMESTAMPTZ(6)");

        let time = ColumnTypeSpec { precision: Some(3), ..kind_spec(ColumnTypeKind::Time) };
        assert_eq!(Dialect::Postgres.map_column_type(&time).unwrap(), "TIME(3)");
    }

    #[test]
    fn binary_length_is_mysql_only() {
        let spec = ColumnTypeSpec { length: Some(16), ..kind_spec(ColumnTypeKind::Binary) };
        assert_eq!(Dialect::Mysql.map_column_type(&spec).unwrap(), "VARBINARY(16)");
        assert_eq!(Dialect::Postgres.map_column_type(&spec).unwrap(), "BYTEA");
        assert_eq!(Dialect::Sqlite.map_column_type(&spec).unwrap(), "BLOB");
    }

    #[test]
    fn float_precision_is_mysql_only() {
        let spec = ColumnTypeSpec { precision: Some(8), scale: Some(2), ..kind_spec(ColumnTypeKind::Float) };
        assert_eq!(Dialect::Mysql.map_column_type(&spec).unwrap(), "FLOAT(8, 2)");
        assert_eq!(Dialect::Postgres.map_column_type(&spec).unwrap(), "REAL");
    }

    #[test]
    fn specific_type_accepts_real_type_names() {
        for raw in ["inet", "tsvector", "geometry(Point, 4326)", "numeric(10, 2)", "double precision"] {
            let spec = ColumnTypeSpec { raw_type: Some(raw.into()), ..kind_spec(ColumnTypeKind::SpecificType) };
            assert_eq!(Dialect::Postgres.map_column_type(&spec).unwrap(), raw, "rejected {raw}");
        }
    }

    /// `specificType` is interpolated verbatim into DDL — it is the one column
    /// type that is an injection surface, so the grammar must hold the line.
    #[test]
    fn specific_type_rejects_injection() {
        for raw in [
            "text); DROP TABLE users; --",
            "text'",
            "text\"",
            "text; SELECT 1",
            "text--",
            "text/*x*/",
            "numeric(10",
            "",
            "   ",
        ] {
            let spec = ColumnTypeSpec { raw_type: Some(raw.into()), ..kind_spec(ColumnTypeKind::SpecificType) };
            assert!(
                Dialect::Postgres.map_column_type(&spec).is_err(),
                "specificType accepted {raw:?}"
            );
        }
    }

    #[test]
    fn specific_type_requires_a_type() {
        let spec = kind_spec(ColumnTypeKind::SpecificType);
        assert!(Dialect::Postgres.map_column_type(&spec).is_err());
    }

    #[test]
    fn from_name_works() {
        assert_eq!(Dialect::from_name("sqlite").unwrap(), Dialect::Sqlite);
        assert_eq!(Dialect::from_name("POSTGRES").unwrap(), Dialect::Postgres);
        assert_eq!(Dialect::from_name("mariadb").unwrap(), Dialect::Mysql);
        assert!(Dialect::from_name("oracle").is_err());
    }

    #[test]
    fn cast_for_postgres_only_and_covers_numeric() {
        // Postgres binds JS strings as text and won't implicitly coerce them to
        // these typed columns — each needs an explicit `::type` cast.
        assert_eq!(Dialect::Postgres.cast_for("numeric"), Some("numeric"));
        assert_eq!(Dialect::Postgres.cast_for("decimal"), Some("numeric"));
        assert_eq!(Dialect::Postgres.cast_for("timestamptz"), Some("timestamptz"));
        assert_eq!(Dialect::Postgres.cast_for("uuid"), Some("uuid"));
        // Nullable integer family: a text-bound NULL needs an explicit cast.
        assert_eq!(Dialect::Postgres.cast_for("integer"), Some("int4"));
        assert_eq!(Dialect::Postgres.cast_for("int"), Some("int4"));
        assert_eq!(Dialect::Postgres.cast_for("bigint"), Some("int8"));
        assert_eq!(Dialect::Postgres.cast_for("smallint"), Some("int2"));
        // Boolean / float family — same text-bound-NULL fix.
        assert_eq!(Dialect::Postgres.cast_for("boolean"), Some("bool"));
        assert_eq!(Dialect::Postgres.cast_for("real"), Some("float4"));
        assert_eq!(Dialect::Postgres.cast_for("double precision"), Some("float8"));
        assert_eq!(Dialect::Postgres.cast_for("float"), Some("float8"));
        assert_eq!(Dialect::Postgres.cast_for("text"), None);
        // SQLite / MySQL coerce text fine — they never get a cast.
        assert_eq!(Dialect::Sqlite.cast_for("numeric"), None);
        assert_eq!(Dialect::Sqlite.cast_for("integer"), None);
        assert_eq!(Dialect::Mysql.cast_for("decimal"), None);
    }

    #[test]
    fn quoting_sqlite_postgres_uses_double_quotes() {
        assert_eq!(Dialect::Sqlite.quote_ident("users").unwrap(), "\"users\"");
        assert_eq!(Dialect::Postgres.quote_ident("users.id").unwrap(), "\"users\".\"id\"");
    }

    #[test]
    fn quoting_mysql_uses_backticks() {
        assert_eq!(Dialect::Mysql.quote_ident("users").unwrap(), "`users`");
    }

    #[test]
    fn quoting_rejects_injection() {
        assert!(Dialect::Sqlite.quote_ident("id\"; DROP").is_err());
        assert!(Dialect::Mysql.quote_ident("id`; DROP").is_err());
        assert!(Dialect::Sqlite.quote_ident("id; DROP").is_err());
    }

    #[test]
    fn star_passes_through() {
        assert_eq!(Dialect::Sqlite.quote_ident("*").unwrap(), "*");
    }

    #[test]
    fn default_wrapping() {
        assert_eq!(Dialect::Postgres.wrap_default("NOW()"), "DEFAULT NOW()");
        assert_eq!(Dialect::Sqlite.wrap_default("CURRENT_TIMESTAMP"), "DEFAULT (CURRENT_TIMESTAMP)");
    }

    #[test]
    fn column_types_per_dialect() {
        let string_255 = ColumnTypeSpec { kind: ColumnTypeKind::String, length: Some(50), precision: None, scale: None, values: None, raw_type: None };
        assert_eq!(Dialect::Postgres.map_column_type(&string_255).unwrap(), "VARCHAR(50)");
        assert_eq!(Dialect::Sqlite.map_column_type(&string_255).unwrap(), "TEXT");
        assert_eq!(Dialect::Mysql.map_column_type(&string_255).unwrap(), "VARCHAR(50)");

        let uuid = ColumnTypeSpec { kind: ColumnTypeKind::Uuid, length: None, precision: None, scale: None, values: None, raw_type: None };
        assert_eq!(Dialect::Postgres.map_column_type(&uuid).unwrap(), "UUID");
        assert_eq!(Dialect::Mysql.map_column_type(&uuid).unwrap(), "CHAR(36)");

        let decimal = ColumnTypeSpec { kind: ColumnTypeKind::Decimal, length: None, precision: Some(12), scale: Some(4), values: None, raw_type: None };
        assert_eq!(Dialect::Postgres.map_column_type(&decimal).unwrap(), "DECIMAL(12, 4)");
        assert_eq!(Dialect::Sqlite.map_column_type(&decimal).unwrap(), "REAL");
    }

    #[test]
    fn new_numeric_and_time_types_map_per_dialect() {
        let spec = |kind| ColumnTypeSpec { kind, length: None, precision: None, scale: None, values: None, raw_type: None };
        // float
        assert_eq!(Dialect::Mysql.map_column_type(&spec(ColumnTypeKind::Float)).unwrap(), "FLOAT");
        assert_eq!(Dialect::Postgres.map_column_type(&spec(ColumnTypeKind::Float)).unwrap(), "REAL");
        assert_eq!(Dialect::Sqlite.map_column_type(&spec(ColumnTypeKind::Float)).unwrap(), "REAL");
        // double
        assert_eq!(Dialect::Postgres.map_column_type(&spec(ColumnTypeKind::Double)).unwrap(), "DOUBLE PRECISION");
        assert_eq!(Dialect::Sqlite.map_column_type(&spec(ColumnTypeKind::Double)).unwrap(), "REAL");
        assert_eq!(Dialect::Mysql.map_column_type(&spec(ColumnTypeKind::Double)).unwrap(), "DOUBLE");
        // time
        assert_eq!(Dialect::Postgres.map_column_type(&spec(ColumnTypeKind::Time)).unwrap(), "TIME");
        assert_eq!(Dialect::Sqlite.map_column_type(&spec(ColumnTypeKind::Time)).unwrap(), "TEXT");
        // tinyint widens to SMALLINT on Postgres (no native tinyint)
        assert_eq!(Dialect::Mysql.map_column_type(&spec(ColumnTypeKind::TinyInt)).unwrap(), "TINYINT");
        assert_eq!(Dialect::Postgres.map_column_type(&spec(ColumnTypeKind::TinyInt)).unwrap(), "SMALLINT");
        assert_eq!(Dialect::Sqlite.map_column_type(&spec(ColumnTypeKind::TinyInt)).unwrap(), "INTEGER");
        // smallint
        assert_eq!(Dialect::Postgres.map_column_type(&spec(ColumnTypeKind::SmallInt)).unwrap(), "SMALLINT");
        assert_eq!(Dialect::Sqlite.map_column_type(&spec(ColumnTypeKind::SmallInt)).unwrap(), "INTEGER");
    }

    #[test]
    fn timestamptz_is_tz_aware_on_postgres_and_degrades_elsewhere() {
        let tz = ColumnTypeSpec { kind: ColumnTypeKind::Timestamptz, length: None, precision: None, scale: None, values: None, raw_type: None };
        assert_eq!(Dialect::Postgres.map_column_type(&tz).unwrap(), "TIMESTAMPTZ");
        assert_eq!(Dialect::Mysql.map_column_type(&tz).unwrap(), "TIMESTAMP");
        assert_eq!(Dialect::Sqlite.map_column_type(&tz).unwrap(), "TEXT");
        // Postgres strict-bind needs a `::timestamptz` cast on text params.
        assert_eq!(Dialect::Postgres.cast_for("timestamptz"), Some("timestamptz"));
    }
}
