/**
 * `schema:generate` — database-first codegen (Adonis Lucid parity). Introspects
 * the live database and writes a `schema.ts` file with one `BaseModel` subclass
 * per table, mirroring Lucid's `schema:generate` → `database/schema.ts`.
 *
 * @example
 *   // commands/schema-generate.ts
 *   import { schemaGenerateCommand } from '@c9up/atlas'
 *   export default schemaGenerateCommand({ outputPath: 'database/schema.ts' })
 */

import * as fsp from "node:fs/promises";
import * as path from "node:path";
import { listUserTables } from "../schema/catalog.js";
import {
	type IntrospectedColumn,
	introspectTable,
} from "../schema/introspect.js";
import { getDb } from "../services/db.js";
import type { AtlasCommand } from "./schemaCheckCommand.js";

export interface SchemaGenerateOptions {
	/** File to write the generated schema classes to (Lucid `outputPath`). */
	outputPath: string;
	/** Extra tables to skip (framework tables are always skipped). */
	excludeTables?: string[];
}

/** `snake_case` / `snake_case_id` → `camelCase`. */
function toCamel(name: string): string {
	return name.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** `snake_case` table → `PascalCase` class stem. */
function toPascal(name: string): string {
	const camel = toCamel(name);
	return camel.charAt(0).toUpperCase() + camel.slice(1);
}

/** Map a raw dialect column type to a TypeScript type. */
function toTsType(rawType: string): string {
	const t = rawType.toLowerCase();
	if (/bool/.test(t)) return "boolean";
	if (/int|serial|decimal|numeric|real|float|double|number/.test(t))
		return "number";
	if (/timestamp|datetime|date|time/.test(t)) return "Date";
	if (/json/.test(t)) return "unknown";
	if (/bytea|blob|binary/.test(t)) return "Uint8Array";
	return "string"; // varchar / text / char / uuid / everything else
}

/** Render one column line: `\t@Column() declare email: string;`. */
function renderColumn(col: IntrospectedColumn): string {
	const decorator = col.primaryKey ? "@PrimaryKey()" : "@Column()";
	const tsType = toTsType(col.type);
	const nullable = col.nullable && !col.primaryKey ? " | null" : "";
	return `\t${decorator} declare ${toCamel(col.name)}: ${tsType}${nullable};`;
}

/** Render one `<Table>Schema extends BaseModel` class. */
function renderClass(table: string, columns: IntrospectedColumn[]): string {
	const body = columns.map(renderColumn).join("\n");
	return (
		`export class ${toPascal(table)}Schema extends BaseModel {\n` +
		`\tstatic table = "${table}";\n\n${body}\n}`
	);
}

/**
 * Render the full `schema.ts` source from introspected tables. Pure — no DB
 * access — so it is unit-testable. Manual edits to the output are lost on
 * regeneration (same contract as Lucid).
 */
export function renderSchemaFile(
	tables: ReadonlyArray<{ table: string; columns: IntrospectedColumn[] }>,
): string {
	const header =
		"// Generated by @c9up/atlas schema:generate — DO NOT EDIT.\n" +
		"// Manual edits are lost on regeneration.\n" +
		'import { BaseModel, Column, PrimaryKey } from "@c9up/atlas";\n';
	if (tables.length === 0) return `${header}\n// (no tables)\n`;
	const classes = tables
		.map((t) => renderClass(t.table, t.columns))
		.join("\n\n");
	return `${header}\n${classes}\n`;
}

/** `schema:generate` — introspect the DB and (re)write the schema file. */
export function schemaGenerateCommand(
	options: SchemaGenerateOptions,
): AtlasCommand {
	return {
		name: "schema:generate",
		description:
			"Introspect the database and generate BaseModel schema classes",
		async run() {
			const db = getDb();
			if (!db) {
				console.error(
					"[atlas] no database connection — is AtlasProvider registered?",
				);
				process.exitCode = 1;
				return;
			}
			const exclude = new Set(options.excludeTables ?? []);
			const names = (await listUserTables(db, db.dialect))
				.filter((n) => !exclude.has(n))
				.sort();

			const tables: Array<{ table: string; columns: IntrospectedColumn[] }> =
				[];
			for (const table of names) {
				const columns = await introspectTable(db, db.dialect, table);
				if (columns) tables.push({ table, columns });
			}

			const source = renderSchemaFile(tables);
			await fsp.mkdir(path.dirname(options.outputPath), { recursive: true });
			await fsp.writeFile(options.outputPath, source);
			console.log(
				`Generated ${options.outputPath} (${tables.length} table${tables.length === 1 ? "" : "s"})`,
			);
		},
	};
}
