/**
 * `schema:generate` — database-first codegen (Adonis Lucid parity). Introspects
 * the live database and writes a `schema.ts` file with one `BaseModel` subclass
 * per table, mirroring Lucid's `schema:generate` → `database/schema.ts`.
 *
 * @example
 *   // commands/schema-generate.ts
 *   import { schemaGenerateCommand } from '@c9up/atlas'
 *   export default schemaGenerateCommand({ outputPath: 'database/schema.ts' })
 */

import * as fsp from "node:fs/promises";
import * as path from "node:path";
import { listUserTables } from "../schema/catalog.js";
import {
	type IntrospectedColumn,
	introspectTable,
} from "../schema/introspect.js";
import { getDb } from "../services/db.js";
import type { AtlasCommand } from "./schemaCheckCommand.js";

export interface SchemaGenerateOptions {
	/** File to write the generated schema classes to (Lucid `outputPath`). */
	outputPath: string;
	/** Extra tables to skip (framework tables are always skipped). */
	excludeTables?: string[];
}

/** `snake_case` / `snake_case_id` → `camelCase`. */
function toCamel(name: string): string {
	return name.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** `snake_case` table → `PascalCase` class stem. */
function toPascal(name: string): string {
	const camel = toCamel(name);
	return camel.charAt(0).toUpperCase() + camel.slice(1);
}

/** `camelCase` → `snake_case`, to detect when a DB column needs `columnName`. */
function toSnake(name: string): string {
	return name.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
}

/** Is this a date/time column (→ `@column.dateTime` + a Chronos `DateTime`)? */
function isDateType(rawType: string): boolean {
	return /timestamp|datetime|date|time/.test(rawType.toLowerCase());
}

/** Map a NON-date raw dialect column type to a TypeScript type. */
function toTsType(rawType: string): string {
	const t = rawType.toLowerCase();
	if (/bool/.test(t)) return "boolean";
	if (/int|serial|real|float|double|number/.test(t)) return "number";
	// decimal/numeric hydrate as strings (atlas keeps precision) — Lucid parity.
	if (/decimal|numeric/.test(t)) return "string";
	if (/json/.test(t)) return "unknown";
	if (/bytea|blob|binary/.test(t)) return "Uint8Array";
	return "string"; // varchar / text / char / uuid / everything else
}

/** `columnName: "..."` fragment when the DB name doesn't round-trip from camelCase. */
function columnNameOpt(col: IntrospectedColumn, prop: string): string {
	return toSnake(prop) === col.name ? "" : `columnName: "${col.name}"`;
}

/** Render one column declaration line (Lucid decorator + typed property). */
function renderColumn(col: IntrospectedColumn): string {
	const prop = toCamel(col.name);
	const cn = columnNameOpt(col, prop);
	if (isDateType(col.type) && !col.primaryKey) {
		const opts = cn ? `{ ${cn} }` : "";
		const nullable = col.nullable ? " | null" : "";
		return `\t@column.dateTime(${opts}) declare ${prop}: DateTime${nullable};`;
	}
	const opts = cn ? `{ ${cn} }` : "";
	const decorator = col.primaryKey ? "@PrimaryKey()" : `@Column(${opts})`;
	const nullable = col.nullable && !col.primaryKey ? " | null" : "";
	return `\t${decorator} declare ${prop}: ${toTsType(col.type)}${nullable};`;
}

/** Render one `<Table>Schema extends BaseModel` class (with Lucid `$columns`). */
function renderClass(table: string, columns: IntrospectedColumn[]): string {
	const className = `${toPascal(table)}Schema`;
	const props = columns.map((c) => toCamel(c.name));
	const cols = props.map((p) => `"${p}"`).join(", ");
	const body = columns.map(renderColumn).join("\n");
	return (
		`export class ${className} extends BaseModel {\n` +
		`\tstatic table = "${table}";\n` +
		`\tstatic $columns = [${cols}] as const;\n` +
		`\t$columns = ${className}.$columns;\n\n${body}\n}`
	);
}

/**
 * Render the full `schema.ts` source from introspected tables. Pure — no DB
 * access — so it is unit-testable. Manual edits to the output are lost on
 * regeneration (same contract as Lucid).
 */
export function renderSchemaFile(
	tables: ReadonlyArray<{ table: string; columns: IntrospectedColumn[] }>,
): string {
	const hasDate = tables.some((t) => t.columns.some((c) => isDateType(c.type)));
	const header =
		"// Generated by @c9up/atlas schema:generate — DO NOT EDIT.\n" +
		"// Manual edits are lost on regeneration.\n" +
		'import { BaseModel, Column, column, PrimaryKey } from "@c9up/atlas";\n' +
		(hasDate ? 'import { DateTime } from "@c9up/chronos";\n' : "");
	if (tables.length === 0) return `${header}\n// (no tables)\n`;
	const classes = tables
		.map((t) => renderClass(t.table, t.columns))
		.join("\n\n");
	return `${header}\n${classes}\n`;
}

/** `schema:generate` — introspect the DB and (re)write the schema file. */
export function schemaGenerateCommand(
	options: SchemaGenerateOptions,
): AtlasCommand {
	return {
		name: "schema:generate",
		description:
			"Introspect the database and generate BaseModel schema classes",
		async run() {
			const db = getDb();
			if (!db) {
				console.error(
					"[atlas] no database connection — is AtlasProvider registered?",
				);
				process.exitCode = 1;
				return;
			}
			const exclude = new Set(options.excludeTables ?? []);
			const names = (await listUserTables(db, db.dialect))
				.filter((n) => !exclude.has(n))
				.sort();

			const tables: Array<{ table: string; columns: IntrospectedColumn[] }> =
				[];
			for (const table of names) {
				const columns = await introspectTable(db, db.dialect, table);
				if (columns) tables.push({ table, columns });
			}

			const source = renderSchemaFile(tables);
			await fsp.mkdir(path.dirname(options.outputPath), { recursive: true });
			await fsp.writeFile(options.outputPath, source);
			console.log(
				`Generated ${options.outputPath} (${tables.length} table${tables.length === 1 ? "" : "s"})`,
			);
		},
	};
}
