/**
 * Migration base class — extend this to create database migrations.
 *
 * @implements FR34
 */

import { Schema } from './SchemaBuilder.js'

/**
 * Base class for all migrations.
 *
 * Usage:
 *   import { Migration } from '@c9up/atlas'
 *
 *   export default class CreateOrders extends Migration {
 *     async up() {
 *       this.schema.createTable('orders', (table) => {
 *         table.id()
 *         table.string('status', 50).notNullable().defaultTo("'pending'")
 *         table.decimal('total', 10, 2).notNullable()
 *         table.timestamps()
 *       })
 *     }
 *
 *     async down() {
 *       this.schema.dropTable('orders')
 *     }
 *   }
 */
export abstract class Migration {
  readonly schema: Schema

  constructor(driver: 'postgres' | 'sqlite' = 'postgres') {
    this.schema = new Schema(driver)
  }

  /** Apply the migration. */
  abstract up(): Promise<void> | void

  /** Rollback the migration. */
  abstract down(): Promise<void> | void

  /** Helper: raw SQL expression (for DEFAULT values). */
  raw(expression: string): string {
    return expression
  }

  /** Helper: NOW() for the current driver. */
  now(): string {
    return 'NOW()'
  }

  /** Get the SQL statements generated by this migration. */
  async getUpSQL(): Promise<string[]> {
    this.schema.reset()
    await this.up()
    return this.schema.toSQL()
  }

  async getDownSQL(): Promise<string[]> {
    this.schema.reset()
    await this.down()
    return this.schema.toSQL()
  }
}
