/**
 * Migration base class — extend this to create database migrations.
 *
 * @implements FR34
 */

import type { AtlasDialect } from "../query/native.js";
import { RawSql } from "../query/QueryBuilder.js";
import type { CatalogConnection } from "./catalog.js";
import { Schema } from "./SchemaBuilder.js";

/**
 * Base class for all migrations.
 *
 * Usage:
 *   import { Migration } from '@c9up/atlas'
 *
 *   export default class CreateOrders extends Migration {
 *     async up() {
 *       this.schema.createTable('orders', (table) => {
 *         table.id()
 *         table.string('status', 50).notNullable().defaultTo("'pending'")
 *         table.decimal('total', 10, 2).notNullable()
 *         table.timestamps()
 *       })
 *     }
 *
 *     async down() {
 *       this.schema.dropTable('orders')
 *     }
 *   }
 */
/**
 * A deferred operation registered with `this.defer()`. Runs after the
 * migration's schema statements, with a live connection handle (execute/query).
 */
export type DeferredMigrationCallback = (
	db: CatalogConnection,
) => Promise<void> | void;

export abstract class Migration {
	readonly schema: Schema;
	readonly #dialect: AtlasDialect;
	#deferred: DeferredMigrationCallback[] = [];

	constructor(dialect?: AtlasDialect) {
		this.schema = new Schema(dialect);
		// Default to sqlite when no dialect is passed — the generator emits
		// sqlite-compatible helpers (`CURRENT_TIMESTAMP`) which happen to work
		// on postgres/mysql too, so this is the safest conservative default.
		this.#dialect = dialect ?? "sqlite";
	}

	/**
	 * Register a callback to run AFTER this migration's schema statements execute
	 * (Adonis Lucid `this.defer`). Typically used to seed data into a table the
	 * same migration just created. The callback gets a live connection handle.
	 *
	 * ⚠️ ATOMICITY DEVIATION FROM LUCID — read before combining defer with DDL.
	 * Lucid runs `defer` callbacks INSIDE the migration transaction, so a failing
	 * callback rolls back the schema too. atlas builds the schema as its own
	 * committed batch, THEN runs deferred callbacks, THEN records the migration.
	 * So if a deferred callback throws, the schema is ALREADY applied but the
	 * migration is NOT recorded — and a plain re-run re-emits `CREATE TABLE …`
	 * against the now-existing table and hard-fails, wedging the pipeline.
	 *
	 * Therefore, when a migration uses `defer` alongside DDL, make BOTH idempotent:
	 * use `createTableIfNotExists` / guarded DDL, and make the deferred work
	 * safe to re-run. (A full fix needs interactive-transaction support in the
	 * runner; until then this is the contract.)
	 */
	defer(callback: DeferredMigrationCallback): void {
		this.#deferred.push(callback);
	}

	/** @internal Return and clear the deferred callbacks — called by the runner. */
	consumeDeferred(): DeferredMigrationCallback[] {
		const deferred = this.#deferred;
		this.#deferred = [];
		return deferred;
	}

	/** Apply the migration. */
	abstract up(): Promise<void> | void;

	/** Rollback the migration. */
	abstract down(): Promise<void> | void;

	/** Helper: raw SQL expression for a column DEFAULT — emitted verbatim, not quoted. */
	raw(expression: string): RawSql {
		return new RawSql(expression);
	}

	/**
	 * Dialect-aware "current timestamp" helper for column defaults.
	 *
	 * - `sqlite`   → `CURRENT_TIMESTAMP` (the only form SQLite understands)
	 * - `postgres` → `NOW()`
	 * - `mysql`    → `NOW()`
	 *
	 * Previously this always returned `NOW()`, which silently broke SQLite
	 * migrations — `NOW()` is not a recognised function there and the column
	 * default would blow up at DDL compile time.
	 */
	now(): RawSql {
		return new RawSql(
			this.#dialect === "sqlite" ? "CURRENT_TIMESTAMP" : "NOW()",
		);
	}

	/**
	 * Get the SQL statements generated by this migration. A `connection` (passed
	 * by the runner) is bound to the schema so `this.schema.hasTable()` /
	 * `hasColumn()` can query the live catalog from inside `up`/`down`.
	 */
	async getUpSQL(connection?: CatalogConnection): Promise<string[]> {
		if (connection) this.schema.bindConnection(connection);
		this.schema.reset();
		this.#deferred = [];
		await this.up();
		return this.schema.toSQL();
	}

	async getDownSQL(connection?: CatalogConnection): Promise<string[]> {
		if (connection) this.schema.bindConnection(connection);
		this.schema.reset();
		this.#deferred = [];
		await this.down();
		return this.schema.toSQL();
	}
}
